// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedGetQuotesParams {
    /// If supplied, filters to quotes of specific version (by CID) of the post record.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Reference (AT-URI) of post record
    pub uri: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedGetQuotesOutput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub posts: Vec<crate::api::app::bsky::FeedDefsPostView>,
    pub uri: crate::syntax::AtUri,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// FeedGetQuotes — Get a list of quotes for a given post.
pub async fn feed_get_quotes(
    client: &crate::xrpc::Client,
    params: &FeedGetQuotesParams,
) -> Result<FeedGetQuotesOutput, crate::xrpc::Error> {
    client.query("app.bsky.feed.getQuotes", params).await
}
