// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedGetTimelineParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub algorithm: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedGetTimelineOutput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub feed: Vec<crate::api::app::bsky::FeedDefsFeedViewPost>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// FeedGetTimeline — Get a view of the requesting account's home timeline. This is expected to be some form of reverse...
pub async fn feed_get_timeline(
    client: &crate::xrpc::Client,
    params: &FeedGetTimelineParams,
) -> Result<FeedGetTimelineOutput, crate::xrpc::Error> {
    client.query("app.bsky.feed.getTimeline", params).await
}
