// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphUnmuteThreadInput {
    pub root: crate::syntax::AtUri,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// GraphUnmuteThread — Unmutes the specified thread. Requires auth.
pub async fn graph_unmute_thread(
    client: &crate::xrpc::Client,
    input: &GraphUnmuteThreadInput,
) -> Result<(), crate::xrpc::Error> {
    let _: serde_json::Value = client
        .procedure("app.bsky.graph.unmuteThread", input)
        .await?;
    Ok(())
}
