// Code generated by lexgen. DO NOT EDIT.

/// GraphStarterpackFeedItem object from app.bsky.graph.starterpack.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphStarterpackFeedItem {
    pub uri: crate::syntax::AtUri,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl GraphStarterpackFeedItem {
    pub fn to_cbor(&self) -> Result<Vec<u8>, crate::cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), crate::cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let count = 1u64;
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("uri")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(self.uri.as_str())?;
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(self.uri.as_str())?;
                pairs.push(("uri", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| crate::cbor::cbor_key_cmp(a.0, b.0));
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                crate::cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }

    pub fn decode_cbor(decoder: &mut crate::cbor::Decoder) -> Result<Self, crate::cbor::CborError> {
        let mut field_uri: Option<crate::syntax::AtUri> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        let mut entries = decoder.map_entries()?;
        while let Some(result) = entries.next_with(|key, decoder| {
            match key {
                "uri" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_uri = Some(
                            crate::syntax::AtUri::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                _ => {
                    let value = decoder.decode()?;
                    let raw = crate::cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
            Ok(())
        }) {
            result?;
        }

        Ok(GraphStarterpackFeedItem {
            uri: field_uri.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'uri'".into())
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }

    #[allow(dead_code)]
    pub(crate) fn from_cbor_value(
        val: crate::cbor::Value<'_>,
    ) -> Result<Self, crate::cbor::CborError> {
        let entries = match val {
            crate::cbor::Value::Map(entries) => entries,
            _ => return Err(crate::cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_uri: Option<crate::syntax::AtUri> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "uri" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_uri = Some(
                            crate::syntax::AtUri::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                _ => {
                    let raw = crate::cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(GraphStarterpackFeedItem {
            uri: field_uri.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'uri'".into())
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

/// A validated CBOR view. Borrowed fields cannot outlive the input.
#[derive(Debug)]
pub struct GraphStarterpackFeedItemCborView<'a> {
    pub uri: crate::syntax::AtUriRef<'a>,
    pub extra_cbor: Vec<(&'a str, &'a [u8])>,
    raw_cbor: &'a [u8],
}
impl<'a> GraphStarterpackFeedItemCborView<'a> {
    #[inline]
    pub fn from_cbor(data: &'a [u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }
    pub fn to_owned(&self) -> Result<GraphStarterpackFeedItem, crate::cbor::CborError> {
        Ok(GraphStarterpackFeedItem {
            uri: self.uri.to_owned(),
            extra: std::collections::HashMap::new(),
            extra_cbor: self
                .extra_cbor
                .iter()
                .map(|(key, value)| ((*key).to_owned(), value.to_vec()))
                .collect(),
        })
    }
    /// The original input, unaffected by changes to public view fields.
    pub fn original_cbor(&self) -> &'a [u8] {
        self.raw_cbor
    }
    #[inline]
    pub fn decode_cbor(
        decoder: &mut crate::cbor::Decoder<'a>,
    ) -> Result<Self, crate::cbor::CborError> {
        let start = decoder.position();
        let mut field_uri: Option<crate::syntax::AtUriRef<'a>> = None;
        let mut extra_cbor = Vec::new();
        let mut entries = decoder.map_entries()?;
        entries.try_field(b"\x63\x75\x72\x69", |decoder| {
            field_uri = Some(
                crate::syntax::AtUriRef::try_from(decoder.text()?)
                    .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
            );
            Ok(())
        })?;
        while let Some(result) = entries.next_raw(|key, decoder| {
            match key {
                b"uri" => {
                    field_uri = Some(
                        crate::syntax::AtUriRef::try_from(decoder.text()?)
                            .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                    );
                }
                _ => {
                    let key = core::str::from_utf8(key).map_err(|_| {
                        crate::cbor::CborError::InvalidCbor("invalid UTF-8 in text string".into())
                    })?;
                    let start = decoder.position();
                    let _ = decoder.decode()?;
                    extra_cbor.push((key, &decoder.raw_input()[start..decoder.position()]));
                }
            }
            Ok(())
        }) {
            result?;
        }
        drop(entries);
        Ok(Self {
            uri: field_uri.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'uri'".into())
            })?,
            extra_cbor,
            raw_cbor: &decoder.raw_input()[start..decoder.position()],
        })
    }
}

/// NSID for the GraphStarterpack record.
pub const NSID_GRAPH_STARTERPACK: &str = "app.bsky.graph.starterpack";

/// GraphStarterpack — Record defining a starter pack of actors and feeds for new users.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphStarterpack {
    /// Record type discriminator (`$type`).
    #[serde(rename = "$type", default = "default_type_graphstarterpack")]
    pub r#type: String,
    pub created_at: crate::syntax::Datetime,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub description_facets: Vec<crate::api::app::bsky::RichtextFacet>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub feeds: Vec<GraphStarterpackFeedItem>,
    /// Reference (AT-URI) to the list record.
    pub list: crate::syntax::AtUri,
    /// Display name for starter pack; can not be empty.
    pub name: String,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

fn default_type_graphstarterpack() -> String {
    "app.bsky.graph.starterpack".to_string()
}

impl GraphStarterpack {
    pub fn to_cbor(&self) -> Result<Vec<u8>, crate::cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), crate::cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 4u64;
            if !self.feeds.is_empty() {
                count += 1;
            }
            if self.description.is_some() {
                count += 1;
            }
            if !self.description_facets.is_empty() {
                count += 1;
            }
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("list")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(self.list.as_str())?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("name")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(&self.name)?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("$type")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(&self.r#type)?;
            if !self.feeds.is_empty() {
                crate::cbor::Encoder::new(&mut *buf).encode_text("feeds")?;
                crate::cbor::Encoder::new(&mut *buf).encode_array_header(self.feeds.len() as u64)?;
                for item in &self.feeds {
                    item.encode_cbor(buf)?;
                }
            }
            crate::cbor::Encoder::new(&mut *buf).encode_text("createdAt")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(self.created_at.as_str())?;
            if self.description.is_some() {
                crate::cbor::Encoder::new(&mut *buf).encode_text("description")?;
                if let Some(ref val) = self.description {
                    crate::cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
            if !self.description_facets.is_empty() {
                crate::cbor::Encoder::new(&mut *buf).encode_text("descriptionFacets")?;
                crate::cbor::Encoder::new(&mut *buf)
                    .encode_array_header(self.description_facets.len() as u64)?;
                for item in &self.description_facets {
                    item.encode_cbor(buf)?;
                }
            }
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(self.list.as_str())?;
                pairs.push(("list", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(&self.name)?;
                pairs.push(("name", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(&self.r#type)?;
                pairs.push(("$type", vbuf));
            }
            if !self.feeds.is_empty() {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_array_header(self.feeds.len() as u64)?;
                for item in &self.feeds {
                    item.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("feeds", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(self.created_at.as_str())?;
                pairs.push(("createdAt", vbuf));
            }
            if self.description.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.description {
                    crate::cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("description", vbuf));
            }
            if !self.description_facets.is_empty() {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf)
                    .encode_array_header(self.description_facets.len() as u64)?;
                for item in &self.description_facets {
                    item.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("descriptionFacets", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| crate::cbor::cbor_key_cmp(a.0, b.0));
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                crate::cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }

    pub fn decode_cbor(decoder: &mut crate::cbor::Decoder) -> Result<Self, crate::cbor::CborError> {
        let mut field_list: Option<crate::syntax::AtUri> = None;
        let mut field_name: Option<String> = None;
        let mut field_type: Option<String> = None;
        let mut field_feeds: Vec<GraphStarterpackFeedItem> = Vec::new();
        let mut field_created_at: Option<crate::syntax::Datetime> = None;
        let mut field_description: Option<String> = None;
        let mut field_description_facets: Vec<crate::api::app::bsky::RichtextFacet> = Vec::new();
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        let mut entries = decoder.map_entries()?;
        while let Some(result) = entries.next_with(|key, decoder| {
            match key {
                "list" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_list = Some(
                            crate::syntax::AtUri::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "name" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_name = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "$type" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_type = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "feeds" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Array(items) = value {
                        for item in items {
                            field_feeds.push(GraphStarterpackFeedItem::from_cbor_value(item)?);
                        }
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
                    }
                }
                "createdAt" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_created_at = Some(
                            crate::syntax::Datetime::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "description" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_description = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "descriptionFacets" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Array(items) = value {
                        for item in items {
                            field_description_facets
                                .push(crate::api::app::bsky::RichtextFacet::from_cbor_value(item)?);
                        }
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
                    }
                }
                _ => {
                    let value = decoder.decode()?;
                    let raw = crate::cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
            Ok(())
        }) {
            result?;
        }

        Ok(GraphStarterpack {
            list: field_list.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'list'".into())
            })?,
            name: field_name.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'name'".into())
            })?,
            r#type: field_type.unwrap_or_else(|| "app.bsky.graph.starterpack".to_string()),
            feeds: field_feeds,
            created_at: field_created_at.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'createdAt'".into())
            })?,
            description: field_description,
            description_facets: field_description_facets,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }

    #[allow(dead_code)]
    pub(crate) fn from_cbor_value(
        val: crate::cbor::Value<'_>,
    ) -> Result<Self, crate::cbor::CborError> {
        let entries = match val {
            crate::cbor::Value::Map(entries) => entries,
            _ => return Err(crate::cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_list: Option<crate::syntax::AtUri> = None;
        let mut field_name: Option<String> = None;
        let mut field_type: Option<String> = None;
        let mut field_feeds: Vec<GraphStarterpackFeedItem> = Vec::new();
        let mut field_created_at: Option<crate::syntax::Datetime> = None;
        let mut field_description: Option<String> = None;
        let mut field_description_facets: Vec<crate::api::app::bsky::RichtextFacet> = Vec::new();
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "list" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_list = Some(
                            crate::syntax::AtUri::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "name" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_name = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "$type" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_type = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "feeds" => {
                    if let crate::cbor::Value::Array(items) = value {
                        for item in items {
                            field_feeds.push(GraphStarterpackFeedItem::from_cbor_value(item)?);
                        }
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
                    }
                }
                "createdAt" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_created_at = Some(
                            crate::syntax::Datetime::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "description" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_description = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "descriptionFacets" => {
                    if let crate::cbor::Value::Array(items) = value {
                        for item in items {
                            field_description_facets
                                .push(crate::api::app::bsky::RichtextFacet::from_cbor_value(item)?);
                        }
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
                    }
                }
                _ => {
                    let raw = crate::cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(GraphStarterpack {
            list: field_list.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'list'".into())
            })?,
            name: field_name.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'name'".into())
            })?,
            r#type: field_type.unwrap_or_else(|| "app.bsky.graph.starterpack".to_string()),
            feeds: field_feeds,
            created_at: field_created_at.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'createdAt'".into())
            })?,
            description: field_description,
            description_facets: field_description_facets,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

/// A validated CBOR view. Borrowed fields cannot outlive the input.
#[derive(Debug)]
pub struct GraphStarterpackCborView<'a> {
    pub list: crate::syntax::AtUriRef<'a>,
    pub name: &'a str,
    pub r#type: &'a str,
    pub feeds: Vec<GraphStarterpackFeedItem>,
    pub created_at: crate::syntax::DatetimeRef<'a>,
    pub description: Option<&'a str>,
    pub description_facets: Vec<crate::api::app::bsky::RichtextFacet>,
    pub extra_cbor: Vec<(&'a str, &'a [u8])>,
    raw_cbor: &'a [u8],
}
impl<'a> GraphStarterpackCborView<'a> {
    #[inline]
    pub fn from_cbor(data: &'a [u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }
    pub fn to_owned(&self) -> Result<GraphStarterpack, crate::cbor::CborError> {
        Ok(GraphStarterpack {
            list: self.list.to_owned(),
            name: self.name.to_owned(),
            r#type: self.r#type.to_owned(),
            feeds: self.feeds.clone(),
            created_at: self.created_at.to_owned(),
            description: self.description.as_ref().map(|value| (*value).to_owned()),
            description_facets: self.description_facets.clone(),
            extra: std::collections::HashMap::new(),
            extra_cbor: self
                .extra_cbor
                .iter()
                .map(|(key, value)| ((*key).to_owned(), value.to_vec()))
                .collect(),
        })
    }
    /// The original input, unaffected by changes to public view fields.
    pub fn original_cbor(&self) -> &'a [u8] {
        self.raw_cbor
    }
    #[inline]
    pub fn decode_cbor(
        decoder: &mut crate::cbor::Decoder<'a>,
    ) -> Result<Self, crate::cbor::CborError> {
        let start = decoder.position();
        let mut field_list: Option<crate::syntax::AtUriRef<'a>> = None;
        let mut field_name: Option<&'a str> = None;
        let mut field_type: Option<&'a str> = None;
        let mut field_feeds: Vec<GraphStarterpackFeedItem> = Vec::new();
        let mut field_created_at: Option<crate::syntax::DatetimeRef<'a>> = None;
        let mut field_description: Option<&'a str> = None;
        let mut field_description_facets: Vec<crate::api::app::bsky::RichtextFacet> = Vec::new();
        let mut extra_cbor = Vec::new();
        let mut entries = decoder.map_entries()?;
        entries.try_field(b"\x64\x6c\x69\x73\x74", |decoder| {
            field_list = Some(
                crate::syntax::AtUriRef::try_from(decoder.text()?)
                    .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
            );
            Ok(())
        })?;
        entries.try_field(b"\x64\x6e\x61\x6d\x65", |decoder| {
            field_name = Some(decoder.text()?);
            Ok(())
        })?;
        entries.try_field(b"\x65\x24\x74\x79\x70\x65", |decoder| {
            field_type = Some(decoder.text()?);
            Ok(())
        })?;
        entries.try_field(b"\x65\x66\x65\x65\x64\x73", |decoder| {
            let value = decoder.decode()?;
            if let crate::cbor::Value::Array(items) = value {
                for item in items {
                    field_feeds.push(GraphStarterpackFeedItem::from_cbor_value(item)?);
                }
            } else {
                return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
            }
            Ok(())
        })?;
        entries.try_field(b"\x69\x63\x72\x65\x61\x74\x65\x64\x41\x74", |decoder| {
            field_created_at = Some(
                crate::syntax::DatetimeRef::try_from(decoder.text()?)
                    .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
            );
            Ok(())
        })?;
        entries.try_field(
            b"\x6b\x64\x65\x73\x63\x72\x69\x70\x74\x69\x6f\x6e",
            |decoder| {
                field_description = Some(decoder.text()?);
                Ok(())
            },
        )?;
        entries.try_field(
            b"\x71\x64\x65\x73\x63\x72\x69\x70\x74\x69\x6f\x6e\x46\x61\x63\x65\x74\x73",
            |decoder| {
                let value = decoder.decode()?;
                if let crate::cbor::Value::Array(items) = value {
                    for item in items {
                        field_description_facets
                            .push(crate::api::app::bsky::RichtextFacet::from_cbor_value(item)?);
                    }
                } else {
                    return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
                }
                Ok(())
            },
        )?;
        while let Some(result) = entries.next_raw(|key, decoder| {
            match key {
                b"list" => {
                    field_list = Some(
                        crate::syntax::AtUriRef::try_from(decoder.text()?)
                            .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                    );
                }
                b"name" => {
                    field_name = Some(decoder.text()?);
                }
                b"$type" => {
                    field_type = Some(decoder.text()?);
                }
                b"feeds" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Array(items) = value {
                        for item in items {
                            field_feeds.push(GraphStarterpackFeedItem::from_cbor_value(item)?);
                        }
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
                    }
                }
                b"createdAt" => {
                    field_created_at = Some(
                        crate::syntax::DatetimeRef::try_from(decoder.text()?)
                            .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                    );
                }
                b"description" => {
                    field_description = Some(decoder.text()?);
                }
                b"descriptionFacets" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Array(items) = value {
                        for item in items {
                            field_description_facets
                                .push(crate::api::app::bsky::RichtextFacet::from_cbor_value(item)?);
                        }
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
                    }
                }
                _ => {
                    let key = core::str::from_utf8(key).map_err(|_| {
                        crate::cbor::CborError::InvalidCbor("invalid UTF-8 in text string".into())
                    })?;
                    let start = decoder.position();
                    let _ = decoder.decode()?;
                    extra_cbor.push((key, &decoder.raw_input()[start..decoder.position()]));
                }
            }
            Ok(())
        }) {
            result?;
        }
        drop(entries);
        Ok(Self {
            list: field_list.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'list'".into())
            })?,
            name: field_name.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'name'".into())
            })?,
            r#type: field_type.unwrap_or("app.bsky.graph.starterpack"),
            feeds: field_feeds,
            created_at: field_created_at.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'createdAt'".into())
            })?,
            description: field_description,
            description_facets: field_description_facets,
            extra_cbor,
            raw_cbor: &decoder.raw_input()[start..decoder.position()],
        })
    }
}
