// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NotificationGetPreferencesParams {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NotificationGetPreferencesOutput {
    pub preferences: crate::api::app::bsky::NotificationDefsPreferences,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// NotificationGetPreferences — Get notification-related preferences for an account. Requires auth.
pub async fn notification_get_preferences(
    client: &crate::xrpc::Client,
    params: &NotificationGetPreferencesParams,
) -> Result<NotificationGetPreferencesOutput, crate::xrpc::Error> {
    client
        .query("app.bsky.notification.getPreferences", params)
        .await
}
