// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoAbortUploadInput {
    pub job_id: String,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VideoAbortUploadOutput {
    /// Present only when state is completed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_job_id: Option<String>,
    /// Present only when state is failed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    pub state: String,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// VideoAbortUpload — Abort an upload only while it is created, releasing its quota reservation immediately. Terminal sessions are unchanged and return their terminal outcome. A finishing session returns UploadNotReady.
pub async fn video_abort_upload(
    client: &crate::xrpc::Client,
    input: &VideoAbortUploadInput,
) -> Result<VideoAbortUploadOutput, crate::xrpc::Error> {
    client.procedure("app.bsky.video.abortUpload", input).await
}
