// Code generated by lexgen. DO NOT EDIT.

/// IdentityDefsIdentityInfo object from com.atproto.identity.defs.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IdentityDefsIdentityInfo {
    pub did: crate::syntax::Did,
    /// The complete DID document for the identity.
    pub did_doc: serde_json::Value,
    /// The validated handle of the account; or 'handle.invalid' if the handle did not bi-directionally match the DID document.
    pub handle: crate::syntax::Handle,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl IdentityDefsIdentityInfo {
    pub fn to_cbor(&self) -> Result<Vec<u8>, crate::cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), crate::cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let count = 2u64;
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("did")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(self.did.as_str())?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("handle")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(self.handle.as_str())?;
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(self.did.as_str())?;
                pairs.push(("did", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(self.handle.as_str())?;
                pairs.push(("handle", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| crate::cbor::cbor_key_cmp(a.0, b.0));
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                crate::cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }

    pub fn decode_cbor(decoder: &mut crate::cbor::Decoder) -> Result<Self, crate::cbor::CborError> {
        let mut field_did: Option<crate::syntax::Did> = None;
        let mut field_handle: Option<crate::syntax::Handle> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        let mut entries = decoder.map_entries()?;
        while let Some(result) = entries.next_with(|key, decoder| {
            match key {
                "did" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_did = Some(
                            crate::syntax::Did::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "handle" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_handle = Some(
                            crate::syntax::Handle::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                _ => {
                    let value = decoder.decode()?;
                    let raw = crate::cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
            Ok(())
        }) {
            result?;
        }

        Ok(IdentityDefsIdentityInfo {
            did: field_did.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'did'".into())
            })?,
            did_doc: Default::default(),
            handle: field_handle.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'handle'".into())
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }

    #[allow(dead_code)]
    pub(crate) fn from_cbor_value(
        val: crate::cbor::Value<'_>,
    ) -> Result<Self, crate::cbor::CborError> {
        let entries = match val {
            crate::cbor::Value::Map(entries) => entries,
            _ => return Err(crate::cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_did: Option<crate::syntax::Did> = None;
        let mut field_handle: Option<crate::syntax::Handle> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "did" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_did = Some(
                            crate::syntax::Did::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "handle" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_handle = Some(
                            crate::syntax::Handle::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                _ => {
                    let raw = crate::cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(IdentityDefsIdentityInfo {
            did: field_did.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'did'".into())
            })?,
            did_doc: Default::default(),
            handle: field_handle.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'handle'".into())
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

/// A validated CBOR view. Borrowed fields cannot outlive the input.
#[derive(Debug)]
pub struct IdentityDefsIdentityInfoCborView<'a> {
    pub did: crate::syntax::Did,
    pub did_doc: serde_json::Value,
    pub handle: crate::syntax::Handle,
    pub extra_cbor: Vec<(&'a str, &'a [u8])>,
    raw_cbor: &'a [u8],
}
impl<'a> IdentityDefsIdentityInfoCborView<'a> {
    #[inline]
    pub fn from_cbor(data: &'a [u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }
    pub fn to_owned(&self) -> Result<IdentityDefsIdentityInfo, crate::cbor::CborError> {
        Ok(IdentityDefsIdentityInfo {
            did: self.did.clone(),
            did_doc: self.did_doc.clone(),
            handle: self.handle.clone(),
            extra: std::collections::HashMap::new(),
            extra_cbor: self
                .extra_cbor
                .iter()
                .map(|(key, value)| ((*key).to_owned(), value.to_vec()))
                .collect(),
        })
    }
    /// The original input, unaffected by changes to public view fields.
    pub fn original_cbor(&self) -> &'a [u8] {
        self.raw_cbor
    }
    #[inline]
    pub fn decode_cbor(
        decoder: &mut crate::cbor::Decoder<'a>,
    ) -> Result<Self, crate::cbor::CborError> {
        let start = decoder.position();
        let mut field_did: Option<crate::syntax::Did> = None;
        let mut field_handle: Option<crate::syntax::Handle> = None;
        let mut extra_cbor = Vec::new();
        let mut entries = decoder.map_entries()?;
        entries.try_field(b"\x63\x64\x69\x64", |decoder| {
            let value = decoder.decode()?;
            if let crate::cbor::Value::Text(s) = value {
                field_did = Some(
                    crate::syntax::Did::try_from(s)
                        .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                );
            } else {
                return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
            }
            Ok(())
        })?;
        entries.try_field(b"\x66\x68\x61\x6e\x64\x6c\x65", |decoder| {
            let value = decoder.decode()?;
            if let crate::cbor::Value::Text(s) = value {
                field_handle = Some(
                    crate::syntax::Handle::try_from(s)
                        .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                );
            } else {
                return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
            }
            Ok(())
        })?;
        while let Some(result) = entries.next_raw(|key, decoder| {
            match key {
                b"did" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_did = Some(
                            crate::syntax::Did::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                b"handle" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_handle = Some(
                            crate::syntax::Handle::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                _ => {
                    let key = core::str::from_utf8(key).map_err(|_| {
                        crate::cbor::CborError::InvalidCbor("invalid UTF-8 in text string".into())
                    })?;
                    let start = decoder.position();
                    let _ = decoder.decode()?;
                    extra_cbor.push((key, &decoder.raw_input()[start..decoder.position()]));
                }
            }
            Ok(())
        }) {
            result?;
        }
        drop(entries);
        Ok(Self {
            did: field_did.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'did'".into())
            })?,
            did_doc: Default::default(),
            handle: field_handle.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'handle'".into())
            })?,
            extra_cbor,
            raw_cbor: &decoder.raw_input()[start..decoder.position()],
        })
    }
}
