// Code generated by lexgen. DO NOT EDIT.

/// ServerRequestAccountDelete — Initiate a user account deletion via email.
pub async fn server_request_account_delete(
    client: &crate::xrpc::Client,
) -> Result<(), crate::xrpc::Error> {
    let _: serde_json::Value = client
        .procedure("com.atproto.server.requestAccountDelete", &())
        .await?;
    Ok(())
}
