// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ContactDismissMatchInput {
    pub subject: ratproto_syntax::Did,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ContactDismissMatchOutput {
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// ContactDismissMatch — Removes a match that was found via contact import. It shouldn't appear again if the same contact ...
pub async fn contact_dismiss_match(
    client: &ratproto_xrpc::Client,
    input: &ContactDismissMatchInput,
) -> Result<ContactDismissMatchOutput, ratproto_xrpc::Error> {
    client
        .procedure("app.bsky.contact.dismissMatch", input)
        .await
}
