// Code generated by lexgen. DO NOT EDIT.

/// NSID for the GraphList record.
pub const NSID_GRAPH_LIST: &str = "app.bsky.graph.list";

/// GraphList record from app.bsky.graph.list.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphList {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<crate::Blob>,
    pub created_at: ratproto_syntax::Datetime,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub description_facets: Vec<crate::app::bsky::RichtextFacet>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<GraphListLabelsUnion>,
    pub name: String,
    pub purpose: crate::app::bsky::GraphDefsListPurpose,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

/// GraphListLabelsUnion is a union type.
#[derive(Debug, Clone)]
pub enum GraphListLabelsUnion {
    LabelDefsSelfLabels(Box<crate::com::atproto::LabelDefsSelfLabels>),
    Unknown(crate::UnknownUnionVariant),
}

impl serde::Serialize for GraphListLabelsUnion {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            GraphListLabelsUnion::LabelDefsSelfLabels(inner) => {
                let mut map =
                    serde_json::to_value(inner.as_ref()).map_err(serde::ser::Error::custom)?;
                if let serde_json::Value::Object(ref mut m) = map {
                    m.insert(
                        "$type".to_string(),
                        serde_json::Value::String("com.atproto.label.defs#selfLabels".to_string()),
                    );
                }
                map.serialize(serializer)
            }
            GraphListLabelsUnion::Unknown(v) => {
                if let Some(ref j) = v.json {
                    j.serialize(serializer)
                } else {
                    Err(serde::ser::Error::custom(
                        "no JSON data for unknown union variant",
                    ))
                }
            }
        }
    }
}

impl<'de> serde::Deserialize<'de> for GraphListLabelsUnion {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = serde_json::Value::deserialize(deserializer)?;
        let type_str = value
            .get("$type")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        match type_str {
            "com.atproto.label.defs#selfLabels" => {
                let inner: crate::com::atproto::LabelDefsSelfLabels =
                    serde_json::from_value(value).map_err(serde::de::Error::custom)?;
                Ok(GraphListLabelsUnion::LabelDefsSelfLabels(Box::new(inner)))
            }
            _ => Ok(GraphListLabelsUnion::Unknown(crate::UnknownUnionVariant {
                r#type: type_str.to_string(),
                json: Some(value),
                cbor: None,
            })),
        }
    }
}

impl GraphListLabelsUnion {
    pub fn to_cbor(&self) -> Result<Vec<u8>, ratproto_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), ratproto_cbor::CborError> {
        match self {
            GraphListLabelsUnion::LabelDefsSelfLabels(inner) => inner.encode_cbor(buf),
            GraphListLabelsUnion::Unknown(v) => {
                if let Some(ref data) = v.cbor {
                    buf.extend_from_slice(data);
                    Ok(())
                } else {
                    Err(ratproto_cbor::CborError::InvalidCbor(
                        "no CBOR data for unknown union variant".into(),
                    ))
                }
            }
        }
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, ratproto_cbor::CborError> {
        let mut decoder = ratproto_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(ratproto_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut ratproto_cbor::Decoder,
    ) -> Result<Self, ratproto_cbor::CborError> {
        // Save position, decode the value, look for $type key.
        let start = decoder.position();
        let val = decoder.decode()?;
        let end = decoder.position();
        let raw = &decoder.raw_input()[start..end];
        let entries = match val {
            ratproto_cbor::Value::Map(entries) => entries,
            _ => {
                return Err(ratproto_cbor::CborError::InvalidCbor(
                    "expected map for union".into(),
                ));
            }
        };
        let type_str = entries
            .iter()
            .find(|(k, _)| *k == "$type")
            .and_then(|(_, v)| match v {
                ratproto_cbor::Value::Text(s) => Some(*s),
                _ => None,
            })
            .unwrap_or_default();
        match type_str {
            "com.atproto.label.defs#selfLabels" => {
                let mut dec = ratproto_cbor::Decoder::new(raw);
                let inner = crate::com::atproto::LabelDefsSelfLabels::decode_cbor(&mut dec)?;
                Ok(GraphListLabelsUnion::LabelDefsSelfLabels(Box::new(inner)))
            }
            _ => Ok(GraphListLabelsUnion::Unknown(crate::UnknownUnionVariant {
                r#type: type_str.to_string(),
                json: None,
                cbor: Some(raw.to_vec()),
            })),
        }
    }
}

impl GraphList {
    pub fn to_cbor(&self) -> Result<Vec<u8>, ratproto_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), ratproto_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 3u64;
            if self.avatar.is_some() {
                count += 1;
            }
            if self.labels.is_some() {
                count += 1;
            }
            if self.description.is_some() {
                count += 1;
            }
            if !self.description_facets.is_empty() {
                count += 1;
            }
            ratproto_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text("name")?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text(&self.name)?;
            if self.avatar.is_some() {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text("avatar")?;
                if let Some(ref val) = self.avatar {
                    val.encode_cbor(buf)?;
                }
            }
            if self.labels.is_some() {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text("labels")?;
                if let Some(ref val) = self.labels {
                    val.encode_cbor(buf)?;
                }
            }
            ratproto_cbor::Encoder::new(&mut *buf).encode_text("purpose")?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text(&self.purpose)?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text("createdAt")?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text(self.created_at.as_str())?;
            if self.description.is_some() {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text("description")?;
                if let Some(ref val) = self.description {
                    ratproto_cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
            if !self.description_facets.is_empty() {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text("descriptionFacets")?;
                ratproto_cbor::Encoder::new(&mut *buf)
                    .encode_array_header(self.description_facets.len() as u64)?;
                for item in &self.description_facets {
                    item.encode_cbor(buf)?;
                }
            }
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                ratproto_cbor::Encoder::new(&mut vbuf).encode_text(&self.name)?;
                pairs.push(("name", vbuf));
            }
            if self.avatar.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.avatar {
                    val.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("avatar", vbuf));
            }
            if self.labels.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.labels {
                    val.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("labels", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                ratproto_cbor::Encoder::new(&mut vbuf).encode_text(&self.purpose)?;
                pairs.push(("purpose", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                ratproto_cbor::Encoder::new(&mut vbuf).encode_text(self.created_at.as_str())?;
                pairs.push(("createdAt", vbuf));
            }
            if self.description.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.description {
                    ratproto_cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("description", vbuf));
            }
            if !self.description_facets.is_empty() {
                let mut vbuf = Vec::new();
                ratproto_cbor::Encoder::new(&mut vbuf)
                    .encode_array_header(self.description_facets.len() as u64)?;
                for item in &self.description_facets {
                    item.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("descriptionFacets", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| ratproto_cbor::cbor_key_cmp(a.0, b.0));
            ratproto_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, ratproto_cbor::CborError> {
        let mut decoder = ratproto_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(ratproto_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut ratproto_cbor::Decoder,
    ) -> Result<Self, ratproto_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            ratproto_cbor::Value::Map(entries) => entries,
            _ => return Err(ratproto_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_name: Option<String> = None;
        let mut field_avatar: Option<crate::Blob> = None;
        let mut field_labels: Option<GraphListLabelsUnion> = None;
        let mut field_purpose: Option<crate::app::bsky::GraphDefsListPurpose> = None;
        let mut field_created_at: Option<ratproto_syntax::Datetime> = None;
        let mut field_description: Option<String> = None;
        let mut field_description_facets: Vec<crate::app::bsky::RichtextFacet> = Vec::new();
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "name" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_name = Some(s.to_string());
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "avatar" => {
                    let raw = ratproto_cbor::encode_value(&value)?;
                    let mut dec = ratproto_cbor::Decoder::new(&raw);
                    field_avatar = Some(crate::Blob::decode_cbor(&mut dec)?);
                }
                "labels" => {
                    let raw = ratproto_cbor::encode_value(&value)?;
                    let mut dec = ratproto_cbor::Decoder::new(&raw);
                    field_labels = Some(GraphListLabelsUnion::decode_cbor(&mut dec)?);
                }
                "purpose" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_purpose = Some(s.to_string());
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "createdAt" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_created_at =
                            Some(ratproto_syntax::Datetime::try_from(s).map_err(|e| {
                                ratproto_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "description" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_description = Some(s.to_string());
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "descriptionFacets" => {
                    if let ratproto_cbor::Value::Array(items) = value {
                        for item in items {
                            let raw = ratproto_cbor::encode_value(&item)?;
                            let mut dec = ratproto_cbor::Decoder::new(&raw);
                            field_description_facets
                                .push(crate::app::bsky::RichtextFacet::decode_cbor(&mut dec)?);
                        }
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected array".into(),
                        ));
                    }
                }
                _ => {
                    let raw = ratproto_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(GraphList {
            name: field_name.ok_or_else(|| {
                ratproto_cbor::CborError::InvalidCbor("missing required field 'name'".into())
            })?,
            avatar: field_avatar,
            labels: field_labels,
            purpose: field_purpose.ok_or_else(|| {
                ratproto_cbor::CborError::InvalidCbor("missing required field 'purpose'".into())
            })?,
            created_at: field_created_at.ok_or_else(|| {
                ratproto_cbor::CborError::InvalidCbor("missing required field 'createdAt'".into())
            })?,
            description: field_description,
            description_facets: field_description_facets,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}
