// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphGetListParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    pub list: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphGetListOutput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub items: Vec<crate::app::bsky::GraphDefsListItemView>,
    pub list: crate::app::bsky::GraphDefsListView,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// GraphGetList — Gets a 'view' (with additional context) of a specified list.
pub async fn graph_get_list(
    client: &ratproto_xrpc::Client,
    params: &GraphGetListParams,
) -> Result<GraphGetListOutput, ratproto_xrpc::Error> {
    client.query("app.bsky.graph.getList", params).await
}
