// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NotificationGetUnreadCountParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub priority: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seen_at: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NotificationGetUnreadCountOutput {
    pub count: i64,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// NotificationGetUnreadCount — Count the number of unread notifications for the requesting account. Requires auth.
pub async fn notification_get_unread_count(
    client: &ratproto_xrpc::Client,
    params: &NotificationGetUnreadCountParams,
) -> Result<NotificationGetUnreadCountOutput, ratproto_xrpc::Error> {
    client
        .query("app.bsky.notification.getUnreadCount", params)
        .await
}
