// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnspeccedGetSuggestedFeedsParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnspeccedGetSuggestedFeedsOutput {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub feeds: Vec<crate::app::bsky::FeedDefsGeneratorView>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// UnspeccedGetSuggestedFeeds — Get a list of suggested feeds
pub async fn unspecced_get_suggested_feeds(
    client: &ratproto_xrpc::Client,
    params: &UnspeccedGetSuggestedFeedsParams,
) -> Result<UnspeccedGetSuggestedFeedsOutput, ratproto_xrpc::Error> {
    client
        .query("app.bsky.unspecced.getSuggestedFeeds", params)
        .await
}
