// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnspeccedGetSuggestedUsersSkeletonParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub viewer: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnspeccedGetSuggestedUsersSkeletonOutput {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dids: Vec<ratproto_syntax::Did>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rec_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rec_id_str: Option<String>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// UnspeccedGetSuggestedUsersSkeleton — Get a skeleton of suggested users. Intended to be called and hydrated by app.bsky.unspecced.getSu...
pub async fn unspecced_get_suggested_users_skeleton(
    client: &ratproto_xrpc::Client,
    params: &UnspeccedGetSuggestedUsersSkeletonParams,
) -> Result<UnspeccedGetSuggestedUsersSkeletonOutput, ratproto_xrpc::Error> {
    client
        .query("app.bsky.unspecced.getSuggestedUsersSkeleton", params)
        .await
}
