// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerReserveSigningKeyInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub did: Option<ratproto_syntax::Did>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerReserveSigningKeyOutput {
    pub signing_key: String,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// ServerReserveSigningKey — Reserve a repo signing key, for use with account creation. Necessary so that a DID PLC update ope...
pub async fn server_reserve_signing_key(
    client: &ratproto_xrpc::Client,
    input: &ServerReserveSigningKeyInput,
) -> Result<ServerReserveSigningKeyOutput, ratproto_xrpc::Error> {
    client
        .procedure("com.atproto.server.reserveSigningKey", input)
        .await
}
