// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerCheckAccountStatusOutput {
    pub activated: bool,
    pub expected_blobs: i64,
    pub imported_blobs: i64,
    pub indexed_records: i64,
    pub private_state_values: i64,
    pub repo_blocks: i64,
    pub repo_commit: String,
    pub repo_rev: String,
    pub valid_did: bool,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// ServerCheckAccountStatus — Returns the status of an account, especially as pertaining to import or recovery. Can be called m...
pub async fn server_check_account_status(
    client: &ratproto_xrpc::Client,
) -> Result<ServerCheckAccountStatusOutput, ratproto_xrpc::Error> {
    client
        .query("com.atproto.server.checkAccountStatus", &())
        .await
}
