// Code generated by lexgen. DO NOT EDIT.

/// SyncListHostsHost object from com.atproto.sync.listHosts.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyncListHostsHost {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account_count: Option<i64>,
    pub hostname: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::com::atproto::SyncDefsHostStatus>,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl SyncListHostsHost {
    pub fn to_cbor(&self) -> Result<Vec<u8>, ratproto_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), ratproto_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 1u64;
            if self.seq.is_some() {
                count += 1;
            }
            if self.status.is_some() {
                count += 1;
            }
            if self.account_count.is_some() {
                count += 1;
            }
            ratproto_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            if self.seq.is_some() {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text("seq")?;
                if let Some(ref val) = self.seq {
                    ratproto_cbor::Encoder::new(&mut *buf).encode_i64(*val)?;
                }
            }
            if self.status.is_some() {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text("status")?;
                if let Some(ref val) = self.status {
                    ratproto_cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
            ratproto_cbor::Encoder::new(&mut *buf).encode_text("hostname")?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text(&self.hostname)?;
            if self.account_count.is_some() {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text("accountCount")?;
                if let Some(ref val) = self.account_count {
                    ratproto_cbor::Encoder::new(&mut *buf).encode_i64(*val)?;
                }
            }
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            if self.seq.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.seq {
                    ratproto_cbor::Encoder::new(&mut vbuf).encode_i64(*val)?;
                }
                pairs.push(("seq", vbuf));
            }
            if self.status.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.status {
                    ratproto_cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("status", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                ratproto_cbor::Encoder::new(&mut vbuf).encode_text(&self.hostname)?;
                pairs.push(("hostname", vbuf));
            }
            if self.account_count.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.account_count {
                    ratproto_cbor::Encoder::new(&mut vbuf).encode_i64(*val)?;
                }
                pairs.push(("accountCount", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| ratproto_cbor::cbor_key_cmp(a.0, b.0));
            ratproto_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, ratproto_cbor::CborError> {
        let mut decoder = ratproto_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(ratproto_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut ratproto_cbor::Decoder,
    ) -> Result<Self, ratproto_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            ratproto_cbor::Value::Map(entries) => entries,
            _ => return Err(ratproto_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_seq: Option<i64> = None;
        let mut field_status: Option<crate::com::atproto::SyncDefsHostStatus> = None;
        let mut field_hostname: Option<String> = None;
        let mut field_account_count: Option<i64> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "seq" => match value {
                    ratproto_cbor::Value::Unsigned(n) => {
                        field_seq = Some(n as i64);
                    }
                    ratproto_cbor::Value::Signed(n) => {
                        field_seq = Some(n);
                    }
                    _ => {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected integer".into(),
                        ));
                    }
                },
                "status" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_status = Some(s.to_string());
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "hostname" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_hostname = Some(s.to_string());
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "accountCount" => match value {
                    ratproto_cbor::Value::Unsigned(n) => {
                        field_account_count = Some(n as i64);
                    }
                    ratproto_cbor::Value::Signed(n) => {
                        field_account_count = Some(n);
                    }
                    _ => {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected integer".into(),
                        ));
                    }
                },
                _ => {
                    let raw = ratproto_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(SyncListHostsHost {
            seq: field_seq,
            status: field_status,
            hostname: field_hostname.ok_or_else(|| {
                ratproto_cbor::CborError::InvalidCbor("missing required field 'hostname'".into())
            })?,
            account_count: field_account_count,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyncListHostsParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyncListHostsOutput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub hosts: Vec<SyncListHostsHost>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// SyncListHosts — Enumerates upstream hosts (eg, PDS or relay instances) that this service consumes from. Implement...
pub async fn sync_list_hosts(
    client: &ratproto_xrpc::Client,
    params: &SyncListHostsParams,
) -> Result<SyncListHostsOutput, ratproto_xrpc::Error> {
    client.query("com.atproto.sync.listHosts", params).await
}
