/// Generate the shared types that go in `src/api/mod.rs`.
pub fn gen_shared_types(top_level_modules: &[&str]) -> String {
    let mut out = String::from("// Code generated by lexgen. DO NOT EDIT.\n\n");

    // Module declarations
    for m in top_level_modules {
        out.push_str(&format!("pub mod {m};\n"));
    }
    out.push('\n');

    // Shared types
    out.push_str(
        r#"/// Raw bytes for use in AT Protocol objects (lexicon `bytes` type).
///
/// Encoded as a DAG-CBOR byte string (major type 2) and, in JSON, as
/// `{"$bytes": "<base64>"}` with unpadded standard base64 (RFC 4648 §4), per
/// the AT Protocol data model. Holds arbitrary binary (including non-UTF-8).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Bytes(pub Vec<u8>);

impl Bytes {
    /// Borrow the raw bytes.
    pub fn as_slice(&self) -> &[u8] {
        &self.0
    }

    pub fn to_cbor(&self) -> Result<Vec<u8>, crate::cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), crate::cbor::CborError> {
        crate::cbor::Encoder::new(&mut *buf).encode_bytes(&self.0)?;
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }

    pub fn decode_cbor(decoder: &mut crate::cbor::Decoder) -> Result<Self, crate::cbor::CborError> {
        match decoder.decode()? {
            crate::cbor::Value::Bytes(b) => Ok(Bytes(b.to_vec())),
            _ => Err(crate::cbor::CborError::InvalidCbor("expected byte string for bytes field".into())),
        }
    }
}

impl serde::Serialize for Bytes {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let encoded = data_encoding::BASE64_NOPAD.encode(&self.0);
        let mut st = serializer.serialize_struct("Bytes", 1)?;
        st.serialize_field("$bytes", &encoded)?;
        st.end()
    }
}

impl<'de> serde::Deserialize<'de> for Bytes {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(serde::Deserialize)]
        struct Repr {
            #[serde(rename = "$bytes")]
            bytes: String,
        }
        let repr = Repr::deserialize(deserializer)?;
        let decoded = data_encoding::BASE64_NOPAD
            .decode(repr.bytes.as_bytes())
            .map_err(serde::de::Error::custom)?;
        Ok(Bytes(decoded))
    }
}

/// A CID link for use in AT Protocol objects.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct CidLink {
    #[serde(rename = "$link")]
    pub link: String,
}

impl CidLink {
    pub fn to_cbor(&self) -> Result<Vec<u8>, crate::cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), crate::cbor::CborError> {
        let cid = self.link.parse::<crate::cbor::Cid>().map_err(|e| crate::cbor::CborError::InvalidCbor(format!("invalid CID: {e}")))?;
        crate::cbor::Encoder::new(&mut *buf).encode_cid(&cid)?;
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }

    pub fn decode_cbor(decoder: &mut crate::cbor::Decoder) -> Result<Self, crate::cbor::CborError> {
        let val = decoder.decode()?;
        if let crate::cbor::Value::Cid(c) = val {
            Ok(CidLink { link: c.to_string() })
        } else {
            Err(crate::cbor::CborError::InvalidCbor("expected CID for CidLink".into()))
        }
    }
}

/// A blob reference for use in AT Protocol objects.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct Blob {
    #[serde(rename = "$type")]
    #[serde(default)]
    pub r#type: String,
    #[serde(default)]
    pub r#ref: Option<CidLink>,
    #[serde(rename = "mimeType")]
    #[serde(default)]
    pub mime_type: String,
    #[serde(default)]
    pub size: i64,
}

impl Blob {
    pub fn to_cbor(&self) -> Result<Vec<u8>, crate::cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), crate::cbor::CborError> {
        // CBOR key order (by encoded length then lex):
        // "ref" (3) < "size" (4) < "$type" (5) < "mimeType" (8)
        let mut count = 3u64; // $type, mimeType, size are always present
        if self.r#ref.is_some() { count += 1; }
        crate::cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
        if let Some(ref cid_link) = self.r#ref {
            crate::cbor::Encoder::new(&mut *buf).encode_text("ref")?;
            cid_link.encode_cbor(buf)?;
        }
        crate::cbor::Encoder::new(&mut *buf).encode_text("size")?;
        crate::cbor::Encoder::new(&mut *buf).encode_i64(self.size)?;
        crate::cbor::Encoder::new(&mut *buf).encode_text("$type")?;
        crate::cbor::Encoder::new(&mut *buf).encode_text(&self.r#type)?;
        crate::cbor::Encoder::new(&mut *buf).encode_text("mimeType")?;
        crate::cbor::Encoder::new(&mut *buf).encode_text(&self.mime_type)?;
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }

    pub fn decode_cbor(decoder: &mut crate::cbor::Decoder) -> Result<Self, crate::cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            crate::cbor::Value::Map(entries) => entries,
            _ => return Err(crate::cbor::CborError::InvalidCbor("expected map for Blob".into())),
        };
        let mut blob = Blob::default();
        for (key, value) in entries {
            match key {
                "$type" => {
                    if let crate::cbor::Value::Text(s) = value {
                        blob.r#type = s.to_string();
                    }
                }
                "ref" if !matches!(value, crate::cbor::Value::Null) => {
                    let raw = crate::cbor::encode_value(&value)?;
                    let mut dec = crate::cbor::Decoder::new(&raw);
                    blob.r#ref = Some(CidLink::decode_cbor(&mut dec)?);
                }
                "mimeType" => {
                    if let crate::cbor::Value::Text(s) = value {
                        blob.mime_type = s.to_string();
                    }
                }
                "size" => {
                    match value {
                        crate::cbor::Value::Unsigned(n) => blob.size = n as i64,
                        crate::cbor::Value::Signed(n) => blob.size = n,
                        _ => {}
                    }
                }
                _ => {}
            }
        }
        Ok(blob)
    }
}

/// An unknown/unrecognized union variant preserved for round-tripping.
#[derive(Debug, Clone)]
pub struct UnknownUnionVariant {
    pub r#type: String,
    pub json: Option<serde_json::Value>,
    pub cbor: Option<Vec<u8>>,
}
"#,
    );

    out
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;

    #[test]
    fn shared_types_contains_cid_link() {
        let code = gen_shared_types(&["app", "com"]);
        assert!(code.contains("pub struct CidLink"));
        assert!(code.contains("pub struct Blob"));
        assert!(code.contains("pub struct UnknownUnionVariant"));
        assert!(code.contains("pub mod app;"));
        assert!(code.contains("pub mod com;"));
    }
}
