// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SignatureFindCorrelationParams {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dids: Vec<String>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SignatureFindCorrelationOutput {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub details: Vec<crate::tools::ozone::SignatureDefsSigDetail>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// SignatureFindCorrelation — Find all correlated threat signatures between 2 or more accounts.
pub async fn signature_find_correlation(
    client: &ratproto_xrpc::Client,
    params: &SignatureFindCorrelationParams,
) -> Result<SignatureFindCorrelationOutput, ratproto_xrpc::Error> {
    client
        .query("tools.ozone.signature.findCorrelation", params)
        .await
}
