// Code generated by lexgen. DO NOT EDIT.

/// VerificationGrantVerificationsGrantError — Error object for failed verifications.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VerificationGrantVerificationsGrantError {
    pub error: String,
    pub subject: ratproto_syntax::Did,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl VerificationGrantVerificationsGrantError {
    pub fn to_cbor(&self) -> Result<Vec<u8>, ratproto_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), ratproto_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let count = 2u64;
            ratproto_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text("error")?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text(&self.error)?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text("subject")?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text(self.subject.as_str())?;
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                ratproto_cbor::Encoder::new(&mut vbuf).encode_text(&self.error)?;
                pairs.push(("error", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                ratproto_cbor::Encoder::new(&mut vbuf).encode_text(self.subject.as_str())?;
                pairs.push(("subject", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| ratproto_cbor::cbor_key_cmp(a.0, b.0));
            ratproto_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, ratproto_cbor::CborError> {
        let mut decoder = ratproto_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(ratproto_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut ratproto_cbor::Decoder,
    ) -> Result<Self, ratproto_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            ratproto_cbor::Value::Map(entries) => entries,
            _ => return Err(ratproto_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_error: Option<String> = None;
        let mut field_subject: Option<ratproto_syntax::Did> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "error" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_error = Some(s.to_string());
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "subject" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_subject =
                            Some(ratproto_syntax::Did::try_from(s).map_err(|e| {
                                ratproto_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                _ => {
                    let raw = ratproto_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(VerificationGrantVerificationsGrantError {
            error: field_error.ok_or_else(|| {
                ratproto_cbor::CborError::InvalidCbor("missing required field 'error'".into())
            })?,
            subject: field_subject.ok_or_else(|| {
                ratproto_cbor::CborError::InvalidCbor("missing required field 'subject'".into())
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VerificationGrantVerificationsInput {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub verifications: Vec<VerificationGrantVerificationsVerificationInput>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VerificationGrantVerificationsOutput {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub failed_verifications: Vec<VerificationGrantVerificationsGrantError>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub verifications: Vec<crate::tools::ozone::VerificationDefsVerificationView>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// VerificationGrantVerifications — Grant verifications to multiple subjects. Allows batch processing of up to 100 verifications at o...
pub async fn verification_grant_verifications(
    client: &ratproto_xrpc::Client,
    input: &VerificationGrantVerificationsInput,
) -> Result<VerificationGrantVerificationsOutput, ratproto_xrpc::Error> {
    client
        .procedure("tools.ozone.verification.grantVerifications", input)
        .await
}

/// VerificationGrantVerificationsVerificationInput object from tools.ozone.verification.grantVerifications.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VerificationGrantVerificationsVerificationInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<ratproto_syntax::Datetime>,
    pub display_name: String,
    pub handle: ratproto_syntax::Handle,
    pub subject: ratproto_syntax::Did,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl VerificationGrantVerificationsVerificationInput {
    pub fn to_cbor(&self) -> Result<Vec<u8>, ratproto_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), ratproto_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 3u64;
            if self.created_at.is_some() {
                count += 1;
            }
            ratproto_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text("handle")?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text(self.handle.as_str())?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text("subject")?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text(self.subject.as_str())?;
            if self.created_at.is_some() {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text("createdAt")?;
                if let Some(ref val) = self.created_at {
                    ratproto_cbor::Encoder::new(&mut *buf).encode_text(val.as_str())?;
                }
            }
            ratproto_cbor::Encoder::new(&mut *buf).encode_text("displayName")?;
            ratproto_cbor::Encoder::new(&mut *buf).encode_text(&self.display_name)?;
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                ratproto_cbor::Encoder::new(&mut vbuf).encode_text(self.handle.as_str())?;
                pairs.push(("handle", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                ratproto_cbor::Encoder::new(&mut vbuf).encode_text(self.subject.as_str())?;
                pairs.push(("subject", vbuf));
            }
            if self.created_at.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.created_at {
                    ratproto_cbor::Encoder::new(&mut vbuf).encode_text(val.as_str())?;
                }
                pairs.push(("createdAt", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                ratproto_cbor::Encoder::new(&mut vbuf).encode_text(&self.display_name)?;
                pairs.push(("displayName", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| ratproto_cbor::cbor_key_cmp(a.0, b.0));
            ratproto_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                ratproto_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, ratproto_cbor::CborError> {
        let mut decoder = ratproto_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(ratproto_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut ratproto_cbor::Decoder,
    ) -> Result<Self, ratproto_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            ratproto_cbor::Value::Map(entries) => entries,
            _ => return Err(ratproto_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_handle: Option<ratproto_syntax::Handle> = None;
        let mut field_subject: Option<ratproto_syntax::Did> = None;
        let mut field_created_at: Option<ratproto_syntax::Datetime> = None;
        let mut field_display_name: Option<String> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "handle" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_handle =
                            Some(ratproto_syntax::Handle::try_from(s).map_err(|e| {
                                ratproto_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "subject" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_subject =
                            Some(ratproto_syntax::Did::try_from(s).map_err(|e| {
                                ratproto_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "createdAt" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_created_at =
                            Some(ratproto_syntax::Datetime::try_from(s).map_err(|e| {
                                ratproto_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "displayName" => {
                    if let ratproto_cbor::Value::Text(s) = value {
                        field_display_name = Some(s.to_string());
                    } else {
                        return Err(ratproto_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                _ => {
                    let raw = ratproto_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(VerificationGrantVerificationsVerificationInput {
            handle: field_handle.ok_or_else(|| {
                ratproto_cbor::CborError::InvalidCbor("missing required field 'handle'".into())
            })?,
            subject: field_subject.ok_or_else(|| {
                ratproto_cbor::CborError::InvalidCbor("missing required field 'subject'".into())
            })?,
            created_at: field_created_at,
            display_name: field_display_name.ok_or_else(|| {
                ratproto_cbor::CborError::InvalidCbor("missing required field 'displayName'".into())
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}
