// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IdentityResolveIdentityParams {
    pub identifier: String,
}

/// IdentityResolveIdentityOutput is an alias.
pub type IdentityResolveIdentityOutput = crate::com::atproto::IdentityDefsIdentityInfo;

/// IdentityResolveIdentity — Resolves an identity (DID or Handle) to a full identity (DID document and verified handle).
pub async fn identity_resolve_identity(
    client: &shrike_xrpc::Client,
    params: &IdentityResolveIdentityParams,
) -> Result<IdentityResolveIdentityOutput, shrike_xrpc::Error> {
    client
        .query("com.atproto.identity.resolveIdentity", params)
        .await
}
