[package]
name = "shrike-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Browser WebAssembly bindings for Shrike"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
shrike = { path = "..", default-features = false, features = ["wasm"] }
bs58.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
serde-wasm-bindgen = "0.6"
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
js-sys.workspace = true

[dev-dependencies]
wasm-bindgen-test = "0.3"

[lints]
workspace = true
