// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GroupAddMembersInput {
    pub convo_id: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub members: Vec<crate::syntax::Did>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GroupAddMembersOutput {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub added_members: Vec<crate::api::chat::bsky::ActorDefsProfileViewBasic>,
    pub convo: crate::api::chat::bsky::ConvoDefsConvoView,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// GroupAddMembers — [NOTE: This is under active development and should be considered unstable while this note is here]. Adds members to a group. The members are added in 'request' status, so they have to accept it. This creates convo memberships.
pub async fn group_add_members(
    client: &crate::xrpc::Client,
    input: &GroupAddMembersInput,
) -> Result<GroupAddMembersOutput, crate::xrpc::Error> {
    client.procedure("chat.bsky.group.addMembers", input).await
}
