// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GroupCreateJoinLinkInput {
    pub convo_id: String,
    pub join_rule: crate::api::chat::bsky::GroupDefsJoinRule,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub require_approval: Option<bool>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GroupCreateJoinLinkOutput {
    pub join_link: crate::api::chat::bsky::GroupDefsJoinLinkView,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// GroupCreateJoinLink — [NOTE: This is under active development and should be considered unstable while this note is here]. Creates a join link for the group convo.
pub async fn group_create_join_link(
    client: &crate::xrpc::Client,
    input: &GroupCreateJoinLinkInput,
) -> Result<GroupCreateJoinLinkOutput, crate::xrpc::Error> {
    client
        .procedure("chat.bsky.group.createJoinLink", input)
        .await
}
