// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModerationUpdateActorAccessInput {
    pub actor: crate::syntax::Did,
    pub allow_access: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// ModerationUpdateActorAccess XRPC procedure.
pub async fn moderation_update_actor_access(
    client: &crate::xrpc::Client,
    input: &ModerationUpdateActorAccessInput,
) -> Result<(), crate::xrpc::Error> {
    let _: serde_json::Value = client
        .procedure("chat.bsky.moderation.updateActorAccess", input)
        .await?;
    Ok(())
}
