// Code generated by lexgen. DO NOT EDIT.

/// CommunicationDefsTemplateView object from tools.ozone.communication.defs.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommunicationDefsTemplateView {
    /// Subject of the message, used in emails.
    pub content_markdown: String,
    pub created_at: crate::syntax::Datetime,
    pub disabled: bool,
    pub id: String,
    /// Message language.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<crate::syntax::Language>,
    /// DID of the user who last updated the template.
    pub last_updated_by: crate::syntax::Did,
    /// Name of the template.
    pub name: String,
    /// Content of the template, can contain markdown and variable placeholders.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    pub updated_at: crate::syntax::Datetime,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl CommunicationDefsTemplateView {
    pub fn to_cbor(&self) -> Result<Vec<u8>, crate::cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), crate::cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 7u64;
            if self.lang.is_some() {
                count += 1;
            }
            if self.subject.is_some() {
                count += 1;
            }
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("id")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(&self.id)?;
            if self.lang.is_some() {
                crate::cbor::Encoder::new(&mut *buf).encode_text("lang")?;
                if let Some(ref val) = self.lang {
                    crate::cbor::Encoder::new(&mut *buf).encode_text(val.as_str())?;
                }
            }
            crate::cbor::Encoder::new(&mut *buf).encode_text("name")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(&self.name)?;
            if self.subject.is_some() {
                crate::cbor::Encoder::new(&mut *buf).encode_text("subject")?;
                if let Some(ref val) = self.subject {
                    crate::cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
            crate::cbor::Encoder::new(&mut *buf).encode_text("disabled")?;
            crate::cbor::Encoder::new(&mut *buf).encode_bool(self.disabled)?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("createdAt")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(self.created_at.as_str())?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("updatedAt")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(self.updated_at.as_str())?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("lastUpdatedBy")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(self.last_updated_by.as_str())?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("contentMarkdown")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(&self.content_markdown)?;
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(&self.id)?;
                pairs.push(("id", vbuf));
            }
            if self.lang.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.lang {
                    crate::cbor::Encoder::new(&mut vbuf).encode_text(val.as_str())?;
                }
                pairs.push(("lang", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(&self.name)?;
                pairs.push(("name", vbuf));
            }
            if self.subject.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.subject {
                    crate::cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("subject", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_bool(self.disabled)?;
                pairs.push(("disabled", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(self.created_at.as_str())?;
                pairs.push(("createdAt", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(self.updated_at.as_str())?;
                pairs.push(("updatedAt", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(self.last_updated_by.as_str())?;
                pairs.push(("lastUpdatedBy", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(&self.content_markdown)?;
                pairs.push(("contentMarkdown", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| crate::cbor::cbor_key_cmp(a.0, b.0));
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                crate::cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }

    pub fn decode_cbor(decoder: &mut crate::cbor::Decoder) -> Result<Self, crate::cbor::CborError> {
        let mut field_id: Option<String> = None;
        let mut field_lang: Option<crate::syntax::Language> = None;
        let mut field_name: Option<String> = None;
        let mut field_subject: Option<String> = None;
        let mut field_disabled: Option<bool> = None;
        let mut field_created_at: Option<crate::syntax::Datetime> = None;
        let mut field_updated_at: Option<crate::syntax::Datetime> = None;
        let mut field_last_updated_by: Option<crate::syntax::Did> = None;
        let mut field_content_markdown: Option<String> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        let mut entries = decoder.map_entries()?;
        while let Some(result) = entries.next_with(|key, decoder| {
            match key {
                "id" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_id = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "lang" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_lang = Some(
                            crate::syntax::Language::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "name" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_name = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "subject" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_subject = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "disabled" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Bool(b) = value {
                        field_disabled = Some(b);
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected bool".into()));
                    }
                }
                "createdAt" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_created_at = Some(
                            crate::syntax::Datetime::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "updatedAt" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_updated_at = Some(
                            crate::syntax::Datetime::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "lastUpdatedBy" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_last_updated_by = Some(
                            crate::syntax::Did::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "contentMarkdown" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_content_markdown = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                _ => {
                    let value = decoder.decode()?;
                    let raw = crate::cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
            Ok(())
        }) {
            result?;
        }

        Ok(CommunicationDefsTemplateView {
            id: field_id.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'id'".into())
            })?,
            lang: field_lang,
            name: field_name.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'name'".into())
            })?,
            subject: field_subject,
            disabled: field_disabled.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'disabled'".into())
            })?,
            created_at: field_created_at.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'createdAt'".into())
            })?,
            updated_at: field_updated_at.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'updatedAt'".into())
            })?,
            last_updated_by: field_last_updated_by.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'lastUpdatedBy'".into())
            })?,
            content_markdown: field_content_markdown.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor(
                    "missing required field 'contentMarkdown'".into(),
                )
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }

    #[allow(dead_code)]
    pub(crate) fn from_cbor_value(
        val: crate::cbor::Value<'_>,
    ) -> Result<Self, crate::cbor::CborError> {
        let entries = match val {
            crate::cbor::Value::Map(entries) => entries,
            _ => return Err(crate::cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_id: Option<String> = None;
        let mut field_lang: Option<crate::syntax::Language> = None;
        let mut field_name: Option<String> = None;
        let mut field_subject: Option<String> = None;
        let mut field_disabled: Option<bool> = None;
        let mut field_created_at: Option<crate::syntax::Datetime> = None;
        let mut field_updated_at: Option<crate::syntax::Datetime> = None;
        let mut field_last_updated_by: Option<crate::syntax::Did> = None;
        let mut field_content_markdown: Option<String> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "id" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_id = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "lang" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_lang = Some(
                            crate::syntax::Language::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "name" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_name = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "subject" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_subject = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "disabled" => {
                    if let crate::cbor::Value::Bool(b) = value {
                        field_disabled = Some(b);
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected bool".into()));
                    }
                }
                "createdAt" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_created_at = Some(
                            crate::syntax::Datetime::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "updatedAt" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_updated_at = Some(
                            crate::syntax::Datetime::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "lastUpdatedBy" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_last_updated_by = Some(
                            crate::syntax::Did::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "contentMarkdown" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_content_markdown = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                _ => {
                    let raw = crate::cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(CommunicationDefsTemplateView {
            id: field_id.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'id'".into())
            })?,
            lang: field_lang,
            name: field_name.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'name'".into())
            })?,
            subject: field_subject,
            disabled: field_disabled.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'disabled'".into())
            })?,
            created_at: field_created_at.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'createdAt'".into())
            })?,
            updated_at: field_updated_at.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'updatedAt'".into())
            })?,
            last_updated_by: field_last_updated_by.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'lastUpdatedBy'".into())
            })?,
            content_markdown: field_content_markdown.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor(
                    "missing required field 'contentMarkdown'".into(),
                )
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

/// A validated CBOR view. Borrowed fields cannot outlive the input.
#[derive(Debug)]
pub struct CommunicationDefsTemplateViewCborView<'a> {
    pub id: &'a str,
    pub lang: Option<crate::syntax::Language>,
    pub name: &'a str,
    pub subject: Option<&'a str>,
    pub disabled: bool,
    pub created_at: crate::syntax::DatetimeRef<'a>,
    pub updated_at: crate::syntax::DatetimeRef<'a>,
    pub last_updated_by: crate::syntax::Did,
    pub content_markdown: &'a str,
    pub extra_cbor: Vec<(&'a str, &'a [u8])>,
    raw_cbor: &'a [u8],
}
impl<'a> CommunicationDefsTemplateViewCborView<'a> {
    #[inline]
    pub fn from_cbor(data: &'a [u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }
    pub fn to_owned(&self) -> Result<CommunicationDefsTemplateView, crate::cbor::CborError> {
        Ok(CommunicationDefsTemplateView {
            id: self.id.to_owned(),
            lang: self.lang.clone(),
            name: self.name.to_owned(),
            subject: self.subject.as_ref().map(|value| (*value).to_owned()),
            disabled: self.disabled,
            created_at: self.created_at.to_owned(),
            updated_at: self.updated_at.to_owned(),
            last_updated_by: self.last_updated_by.clone(),
            content_markdown: self.content_markdown.to_owned(),
            extra: std::collections::HashMap::new(),
            extra_cbor: self
                .extra_cbor
                .iter()
                .map(|(key, value)| ((*key).to_owned(), value.to_vec()))
                .collect(),
        })
    }
    /// The original input, unaffected by changes to public view fields.
    pub fn original_cbor(&self) -> &'a [u8] {
        self.raw_cbor
    }
    #[inline]
    pub fn decode_cbor(
        decoder: &mut crate::cbor::Decoder<'a>,
    ) -> Result<Self, crate::cbor::CborError> {
        let start = decoder.position();
        let mut field_id: Option<&'a str> = None;
        let mut field_lang: Option<crate::syntax::Language> = None;
        let mut field_name: Option<&'a str> = None;
        let mut field_subject: Option<&'a str> = None;
        let mut field_disabled: Option<bool> = None;
        let mut field_created_at: Option<crate::syntax::DatetimeRef<'a>> = None;
        let mut field_updated_at: Option<crate::syntax::DatetimeRef<'a>> = None;
        let mut field_last_updated_by: Option<crate::syntax::Did> = None;
        let mut field_content_markdown: Option<&'a str> = None;
        let mut extra_cbor = Vec::new();
        let mut entries = decoder.map_entries()?;
        entries.try_field(b"\x62\x69\x64", |decoder| {
            field_id = Some(decoder.text()?);
            Ok(())
        })?;
        entries.try_field(b"\x64\x6c\x61\x6e\x67", |decoder| {
            let value = decoder.decode()?;
            if let crate::cbor::Value::Text(s) = value {
                field_lang = Some(
                    crate::syntax::Language::try_from(s)
                        .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                );
            } else {
                return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
            }
            Ok(())
        })?;
        entries.try_field(b"\x64\x6e\x61\x6d\x65", |decoder| {
            field_name = Some(decoder.text()?);
            Ok(())
        })?;
        entries.try_field(b"\x67\x73\x75\x62\x6a\x65\x63\x74", |decoder| {
            field_subject = Some(decoder.text()?);
            Ok(())
        })?;
        entries.try_field(b"\x68\x64\x69\x73\x61\x62\x6c\x65\x64", |decoder| {
            let value = decoder.decode()?;
            if let crate::cbor::Value::Bool(b) = value {
                field_disabled = Some(b);
            } else {
                return Err(crate::cbor::CborError::InvalidCbor("expected bool".into()));
            }
            Ok(())
        })?;
        entries.try_field(b"\x69\x63\x72\x65\x61\x74\x65\x64\x41\x74", |decoder| {
            field_created_at = Some(
                crate::syntax::DatetimeRef::try_from(decoder.text()?)
                    .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
            );
            Ok(())
        })?;
        entries.try_field(b"\x69\x75\x70\x64\x61\x74\x65\x64\x41\x74", |decoder| {
            field_updated_at = Some(
                crate::syntax::DatetimeRef::try_from(decoder.text()?)
                    .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
            );
            Ok(())
        })?;
        entries.try_field(
            b"\x6d\x6c\x61\x73\x74\x55\x70\x64\x61\x74\x65\x64\x42\x79",
            |decoder| {
                let value = decoder.decode()?;
                if let crate::cbor::Value::Text(s) = value {
                    field_last_updated_by = Some(
                        crate::syntax::Did::try_from(s)
                            .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                    );
                } else {
                    return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                }
                Ok(())
            },
        )?;
        entries.try_field(
            b"\x6f\x63\x6f\x6e\x74\x65\x6e\x74\x4d\x61\x72\x6b\x64\x6f\x77\x6e",
            |decoder| {
                field_content_markdown = Some(decoder.text()?);
                Ok(())
            },
        )?;
        while let Some(result) = entries.next_raw(|key, decoder| {
            match key {
                b"id" => {
                    field_id = Some(decoder.text()?);
                }
                b"lang" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_lang = Some(
                            crate::syntax::Language::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                b"name" => {
                    field_name = Some(decoder.text()?);
                }
                b"subject" => {
                    field_subject = Some(decoder.text()?);
                }
                b"disabled" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Bool(b) = value {
                        field_disabled = Some(b);
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected bool".into()));
                    }
                }
                b"createdAt" => {
                    field_created_at = Some(
                        crate::syntax::DatetimeRef::try_from(decoder.text()?)
                            .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                    );
                }
                b"updatedAt" => {
                    field_updated_at = Some(
                        crate::syntax::DatetimeRef::try_from(decoder.text()?)
                            .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                    );
                }
                b"lastUpdatedBy" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Text(s) = value {
                        field_last_updated_by = Some(
                            crate::syntax::Did::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                b"contentMarkdown" => {
                    field_content_markdown = Some(decoder.text()?);
                }
                _ => {
                    let key = core::str::from_utf8(key).map_err(|_| {
                        crate::cbor::CborError::InvalidCbor("invalid UTF-8 in text string".into())
                    })?;
                    let start = decoder.position();
                    let _ = decoder.decode()?;
                    extra_cbor.push((key, &decoder.raw_input()[start..decoder.position()]));
                }
            }
            Ok(())
        }) {
            result?;
        }
        drop(entries);
        Ok(Self {
            id: field_id.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'id'".into())
            })?,
            lang: field_lang,
            name: field_name.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'name'".into())
            })?,
            subject: field_subject,
            disabled: field_disabled.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'disabled'".into())
            })?,
            created_at: field_created_at.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'createdAt'".into())
            })?,
            updated_at: field_updated_at.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'updatedAt'".into())
            })?,
            last_updated_by: field_last_updated_by.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'lastUpdatedBy'".into())
            })?,
            content_markdown: field_content_markdown.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor(
                    "missing required field 'contentMarkdown'".into(),
                )
            })?,
            extra_cbor,
            raw_cbor: &decoder.raw_input()[start..decoder.position()],
        })
    }
}
