// Code generated by lexgen. DO NOT EDIT.

/// CommunicationDefsTemplateView object from tools.ozone.communication.defs.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommunicationDefsTemplateView {
    pub content_markdown: String,
    pub created_at: crate::syntax::Datetime,
    pub disabled: bool,
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lang: Option<crate::syntax::Language>,
    pub last_updated_by: crate::syntax::Did,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    pub updated_at: crate::syntax::Datetime,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl CommunicationDefsTemplateView {
    pub fn to_cbor(&self) -> Result<Vec<u8>, crate::cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), crate::cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 7u64;
            if self.lang.is_some() {
                count += 1;
            }
            if self.subject.is_some() {
                count += 1;
            }
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("id")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(&self.id)?;
            if self.lang.is_some() {
                crate::cbor::Encoder::new(&mut *buf).encode_text("lang")?;
                if let Some(ref val) = self.lang {
                    crate::cbor::Encoder::new(&mut *buf).encode_text(val.as_str())?;
                }
            }
            crate::cbor::Encoder::new(&mut *buf).encode_text("name")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(&self.name)?;
            if self.subject.is_some() {
                crate::cbor::Encoder::new(&mut *buf).encode_text("subject")?;
                if let Some(ref val) = self.subject {
                    crate::cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
            crate::cbor::Encoder::new(&mut *buf).encode_text("disabled")?;
            crate::cbor::Encoder::new(&mut *buf).encode_bool(self.disabled)?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("createdAt")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(self.created_at.as_str())?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("updatedAt")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(self.updated_at.as_str())?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("lastUpdatedBy")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(self.last_updated_by.as_str())?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("contentMarkdown")?;
            crate::cbor::Encoder::new(&mut *buf).encode_text(&self.content_markdown)?;
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(&self.id)?;
                pairs.push(("id", vbuf));
            }
            if self.lang.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.lang {
                    crate::cbor::Encoder::new(&mut vbuf).encode_text(val.as_str())?;
                }
                pairs.push(("lang", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(&self.name)?;
                pairs.push(("name", vbuf));
            }
            if self.subject.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.subject {
                    crate::cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("subject", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_bool(self.disabled)?;
                pairs.push(("disabled", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(self.created_at.as_str())?;
                pairs.push(("createdAt", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(self.updated_at.as_str())?;
                pairs.push(("updatedAt", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(self.last_updated_by.as_str())?;
                pairs.push(("lastUpdatedBy", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf).encode_text(&self.content_markdown)?;
                pairs.push(("contentMarkdown", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| crate::cbor::cbor_key_cmp(a.0, b.0));
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                crate::cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }

    pub fn decode_cbor(decoder: &mut crate::cbor::Decoder) -> Result<Self, crate::cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            crate::cbor::Value::Map(entries) => entries,
            _ => return Err(crate::cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_id: Option<String> = None;
        let mut field_lang: Option<crate::syntax::Language> = None;
        let mut field_name: Option<String> = None;
        let mut field_subject: Option<String> = None;
        let mut field_disabled: Option<bool> = None;
        let mut field_created_at: Option<crate::syntax::Datetime> = None;
        let mut field_updated_at: Option<crate::syntax::Datetime> = None;
        let mut field_last_updated_by: Option<crate::syntax::Did> = None;
        let mut field_content_markdown: Option<String> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "id" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_id = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "lang" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_lang = Some(
                            crate::syntax::Language::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "name" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_name = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "subject" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_subject = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "disabled" => {
                    if let crate::cbor::Value::Bool(b) = value {
                        field_disabled = Some(b);
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected bool".into()));
                    }
                }
                "createdAt" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_created_at = Some(
                            crate::syntax::Datetime::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "updatedAt" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_updated_at = Some(
                            crate::syntax::Datetime::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "lastUpdatedBy" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_last_updated_by = Some(
                            crate::syntax::Did::try_from(s)
                                .map_err(|e| crate::cbor::CborError::InvalidCbor(e.to_string()))?,
                        );
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "contentMarkdown" => {
                    if let crate::cbor::Value::Text(s) = value {
                        field_content_markdown = Some(s.to_string());
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                _ => {
                    let raw = crate::cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(CommunicationDefsTemplateView {
            id: field_id.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'id'".into())
            })?,
            lang: field_lang,
            name: field_name.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'name'".into())
            })?,
            subject: field_subject,
            disabled: field_disabled.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'disabled'".into())
            })?,
            created_at: field_created_at.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'createdAt'".into())
            })?,
            updated_at: field_updated_at.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'updatedAt'".into())
            })?,
            last_updated_by: field_last_updated_by.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'lastUpdatedBy'".into())
            })?,
            content_markdown: field_content_markdown.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor(
                    "missing required field 'contentMarkdown'".into(),
                )
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}
