// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModerationGetEventParams {
    pub id: i64,
}

/// ModerationGetEventOutput is an alias.
pub type ModerationGetEventOutput = crate::api::tools::ozone::ModerationDefsModEventViewDetail;

/// ModerationGetEvent — Get details about a moderation event.
pub async fn moderation_get_event(
    client: &crate::xrpc::Client,
    params: &ModerationGetEventParams,
) -> Result<ModerationGetEventOutput, crate::xrpc::Error> {
    client
        .query("tools.ozone.moderation.getEvent", params)
        .await
}
