// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QueueAssignModeratorInput {
    /// DID to be assigned.
    pub did: String,
    /// The ID of the queue to assign the user to.
    pub queue_id: i64,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// QueueAssignModeratorOutput is an alias.
pub type QueueAssignModeratorOutput = crate::api::tools::ozone::QueueDefsAssignmentView;

/// QueueAssignModerator — Assign a user to a queue.
pub async fn queue_assign_moderator(
    client: &crate::xrpc::Client,
    input: &QueueAssignModeratorInput,
) -> Result<QueueAssignModeratorOutput, crate::xrpc::Error> {
    client
        .procedure("tools.ozone.queue.assignModerator", input)
        .await
}
