// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SignatureFindRelatedAccountsParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    pub did: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SignatureFindRelatedAccountsOutput {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub accounts: Vec<SignatureFindRelatedAccountsRelatedAccount>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// SignatureFindRelatedAccounts — Get accounts that share some matching threat signatures with the root account.
pub async fn signature_find_related_accounts(
    client: &crate::xrpc::Client,
    params: &SignatureFindRelatedAccountsParams,
) -> Result<SignatureFindRelatedAccountsOutput, crate::xrpc::Error> {
    client
        .query("tools.ozone.signature.findRelatedAccounts", params)
        .await
}

/// SignatureFindRelatedAccountsRelatedAccount object from tools.ozone.signature.findRelatedAccounts.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SignatureFindRelatedAccountsRelatedAccount {
    pub account: crate::api::com::atproto::AdminDefsAccountView,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub similarities: Vec<crate::api::tools::ozone::SignatureDefsSigDetail>,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl SignatureFindRelatedAccountsRelatedAccount {
    pub fn to_cbor(&self) -> Result<Vec<u8>, crate::cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), crate::cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 1u64;
            if !self.similarities.is_empty() {
                count += 1;
            }
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            crate::cbor::Encoder::new(&mut *buf).encode_text("account")?;
            self.account.encode_cbor(buf)?;
            if !self.similarities.is_empty() {
                crate::cbor::Encoder::new(&mut *buf).encode_text("similarities")?;
                crate::cbor::Encoder::new(&mut *buf)
                    .encode_array_header(self.similarities.len() as u64)?;
                for item in &self.similarities {
                    item.encode_cbor(buf)?;
                }
            }
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                self.account.encode_cbor(&mut vbuf)?;
                pairs.push(("account", vbuf));
            }
            if !self.similarities.is_empty() {
                let mut vbuf = Vec::new();
                crate::cbor::Encoder::new(&mut vbuf)
                    .encode_array_header(self.similarities.len() as u64)?;
                for item in &self.similarities {
                    item.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("similarities", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| crate::cbor::cbor_key_cmp(a.0, b.0));
            crate::cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                crate::cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }

    pub fn decode_cbor(decoder: &mut crate::cbor::Decoder) -> Result<Self, crate::cbor::CborError> {
        let mut field_account: Option<crate::api::com::atproto::AdminDefsAccountView> = None;
        let mut field_similarities: Vec<crate::api::tools::ozone::SignatureDefsSigDetail> =
            Vec::new();
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        let mut entries = decoder.map_entries()?;
        while let Some(result) = entries.next_with(|key, decoder| {
            match key {
                "account" => {
                    field_account = Some(
                        crate::api::com::atproto::AdminDefsAccountView::decode_cbor(decoder)?,
                    );
                }
                "similarities" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Array(items) = value {
                        for item in items {
                            field_similarities.push(
                                crate::api::tools::ozone::SignatureDefsSigDetail::from_cbor_value(
                                    item,
                                )?,
                            );
                        }
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
                    }
                }
                _ => {
                    let value = decoder.decode()?;
                    let raw = crate::cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
            Ok(())
        }) {
            result?;
        }

        Ok(SignatureFindRelatedAccountsRelatedAccount {
            account: field_account.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'account'".into())
            })?,
            similarities: field_similarities,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }

    #[allow(dead_code)]
    pub(crate) fn from_cbor_value(
        val: crate::cbor::Value<'_>,
    ) -> Result<Self, crate::cbor::CborError> {
        let entries = match val {
            crate::cbor::Value::Map(entries) => entries,
            _ => return Err(crate::cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_account: Option<crate::api::com::atproto::AdminDefsAccountView> = None;
        let mut field_similarities: Vec<crate::api::tools::ozone::SignatureDefsSigDetail> =
            Vec::new();
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "account" => {
                    field_account = Some(
                        crate::api::com::atproto::AdminDefsAccountView::from_cbor_value(value)?,
                    );
                }
                "similarities" => {
                    if let crate::cbor::Value::Array(items) = value {
                        for item in items {
                            field_similarities.push(
                                crate::api::tools::ozone::SignatureDefsSigDetail::from_cbor_value(
                                    item,
                                )?,
                            );
                        }
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
                    }
                }
                _ => {
                    let raw = crate::cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(SignatureFindRelatedAccountsRelatedAccount {
            account: field_account.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'account'".into())
            })?,
            similarities: field_similarities,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

/// A validated CBOR view. Borrowed fields cannot outlive the input.
#[derive(Debug)]
pub struct SignatureFindRelatedAccountsRelatedAccountCborView<'a> {
    pub account: crate::api::com::atproto::AdminDefsAccountViewCborView<'a>,
    pub similarities: Vec<crate::api::tools::ozone::SignatureDefsSigDetail>,
    pub extra_cbor: Vec<(&'a str, &'a [u8])>,
    raw_cbor: &'a [u8],
}
impl<'a> SignatureFindRelatedAccountsRelatedAccountCborView<'a> {
    #[inline]
    pub fn from_cbor(data: &'a [u8]) -> Result<Self, crate::cbor::CborError> {
        let mut decoder = crate::cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(crate::cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }
    pub fn to_owned(
        &self,
    ) -> Result<SignatureFindRelatedAccountsRelatedAccount, crate::cbor::CborError> {
        Ok(SignatureFindRelatedAccountsRelatedAccount {
            account: self.account.to_owned()?,
            similarities: self.similarities.clone(),
            extra: std::collections::HashMap::new(),
            extra_cbor: self
                .extra_cbor
                .iter()
                .map(|(key, value)| ((*key).to_owned(), value.to_vec()))
                .collect(),
        })
    }
    /// The original input, unaffected by changes to public view fields.
    pub fn original_cbor(&self) -> &'a [u8] {
        self.raw_cbor
    }
    #[inline]
    pub fn decode_cbor(
        decoder: &mut crate::cbor::Decoder<'a>,
    ) -> Result<Self, crate::cbor::CborError> {
        let start = decoder.position();
        let mut field_account: Option<crate::api::com::atproto::AdminDefsAccountViewCborView<'a>> =
            None;
        let mut field_similarities: Vec<crate::api::tools::ozone::SignatureDefsSigDetail> =
            Vec::new();
        let mut extra_cbor = Vec::new();
        let mut entries = decoder.map_entries()?;
        entries.try_field(b"\x67\x61\x63\x63\x6f\x75\x6e\x74", |decoder| {
            field_account =
                Some(crate::api::com::atproto::AdminDefsAccountViewCborView::decode_cbor(decoder)?);
            Ok(())
        })?;
        entries.try_field(
            b"\x6c\x73\x69\x6d\x69\x6c\x61\x72\x69\x74\x69\x65\x73",
            |decoder| {
                let value = decoder.decode()?;
                if let crate::cbor::Value::Array(items) = value {
                    for item in items {
                        field_similarities.push(
                            crate::api::tools::ozone::SignatureDefsSigDetail::from_cbor_value(
                                item,
                            )?,
                        );
                    }
                } else {
                    return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
                }
                Ok(())
            },
        )?;
        while let Some(result) = entries.next_raw(|key, decoder| {
            match key {
                b"account" => {
                    field_account = Some(
                        crate::api::com::atproto::AdminDefsAccountViewCborView::decode_cbor(
                            decoder,
                        )?,
                    );
                }
                b"similarities" => {
                    let value = decoder.decode()?;
                    if let crate::cbor::Value::Array(items) = value {
                        for item in items {
                            field_similarities.push(
                                crate::api::tools::ozone::SignatureDefsSigDetail::from_cbor_value(
                                    item,
                                )?,
                            );
                        }
                    } else {
                        return Err(crate::cbor::CborError::InvalidCbor("expected array".into()));
                    }
                }
                _ => {
                    let key = core::str::from_utf8(key).map_err(|_| {
                        crate::cbor::CborError::InvalidCbor("invalid UTF-8 in text string".into())
                    })?;
                    let start = decoder.position();
                    let _ = decoder.decode()?;
                    extra_cbor.push((key, &decoder.raw_input()[start..decoder.position()]));
                }
            }
            Ok(())
        }) {
            result?;
        }
        drop(entries);
        Ok(Self {
            account: field_account.ok_or_else(|| {
                crate::cbor::CborError::InvalidCbor("missing required field 'account'".into())
            })?,
            similarities: field_similarities,
            extra_cbor,
            raw_cbor: &decoder.raw_input()[start..decoder.position()],
        })
    }
}
