// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModerationListScheduledActionsInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ends_before: Option<shrike_syntax::Datetime>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub starts_after: Option<shrike_syntax::Datetime>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub statuses: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub subjects: Vec<shrike_syntax::Did>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModerationListScheduledActionsOutput {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub actions: Vec<crate::tools::ozone::ModerationDefsScheduledActionView>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// ModerationListScheduledActions — List scheduled moderation actions with optional filtering
pub async fn moderation_list_scheduled_actions(
    client: &shrike_xrpc::Client,
    input: &ModerationListScheduledActionsInput,
) -> Result<ModerationListScheduledActionsOutput, shrike_xrpc::Error> {
    client
        .procedure("tools.ozone.moderation.listScheduledActions", input)
        .await
}
