// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModerationGetRepoParams {
    pub did: String,
}

/// ModerationGetRepoOutput is an alias.
pub type ModerationGetRepoOutput = crate::tools::ozone::ModerationDefsRepoViewDetail;

/// ModerationGetRepo — Get details about a repository.
pub async fn moderation_get_repo(
    client: &shrike_xrpc::Client,
    params: &ModerationGetRepoParams,
) -> Result<ModerationGetRepoOutput, shrike_xrpc::Error> {
    client.query("tools.ozone.moderation.getRepo", params).await
}
