// Code generated by lexgen. DO NOT EDIT.

/// EmbedVideoCaption object from app.bsky.embed.video.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EmbedVideoCaption {
    pub file: crate::Blob,
    pub lang: shrike_syntax::Language,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl EmbedVideoCaption {
    pub fn to_cbor(&self) -> Result<Vec<u8>, shrike_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), shrike_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let count = 2u64;
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("file")?;
            self.file.encode_cbor(buf)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("lang")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(self.lang.as_str())?;
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                self.file.encode_cbor(&mut vbuf)?;
                pairs.push(("file", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(self.lang.as_str())?;
                pairs.push(("lang", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| shrike_cbor::cbor_key_cmp(a.0, b.0));
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, shrike_cbor::CborError> {
        let mut decoder = shrike_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(shrike_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut shrike_cbor::Decoder,
    ) -> Result<Self, shrike_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            shrike_cbor::Value::Map(entries) => entries,
            _ => return Err(shrike_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_file: Option<crate::Blob> = None;
        let mut field_lang: Option<shrike_syntax::Language> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "file" => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    let mut dec = shrike_cbor::Decoder::new(&raw);
                    field_file = Some(crate::Blob::decode_cbor(&mut dec)?);
                }
                "lang" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_lang =
                            Some(shrike_syntax::Language::try_from(s).map_err(|e| {
                                shrike_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                _ => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(EmbedVideoCaption {
            file: field_file.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'file'".into())
            })?,
            lang: field_lang.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'lang'".into())
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

/// EmbedVideo object from app.bsky.embed.video.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EmbedVideo {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aspect_ratio: Option<crate::app::bsky::EmbedDefsAspectRatio>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub captions: Vec<EmbedVideoCaption>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub presentation: Option<String>,
    pub video: crate::Blob,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl EmbedVideo {
    pub fn to_cbor(&self) -> Result<Vec<u8>, shrike_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), shrike_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 1u64;
            if self.alt.is_some() {
                count += 1;
            }
            if !self.captions.is_empty() {
                count += 1;
            }
            if self.aspect_ratio.is_some() {
                count += 1;
            }
            if self.presentation.is_some() {
                count += 1;
            }
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            if self.alt.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("alt")?;
                if let Some(ref val) = self.alt {
                    shrike_cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
            shrike_cbor::Encoder::new(&mut *buf).encode_text("video")?;
            self.video.encode_cbor(buf)?;
            if !self.captions.is_empty() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("captions")?;
                shrike_cbor::Encoder::new(&mut *buf)
                    .encode_array_header(self.captions.len() as u64)?;
                for item in &self.captions {
                    item.encode_cbor(buf)?;
                }
            }
            if self.aspect_ratio.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("aspectRatio")?;
                if let Some(ref val) = self.aspect_ratio {
                    val.encode_cbor(buf)?;
                }
            }
            if self.presentation.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("presentation")?;
                if let Some(ref val) = self.presentation {
                    shrike_cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            if self.alt.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.alt {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("alt", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                self.video.encode_cbor(&mut vbuf)?;
                pairs.push(("video", vbuf));
            }
            if !self.captions.is_empty() {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf)
                    .encode_array_header(self.captions.len() as u64)?;
                for item in &self.captions {
                    item.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("captions", vbuf));
            }
            if self.aspect_ratio.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.aspect_ratio {
                    val.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("aspectRatio", vbuf));
            }
            if self.presentation.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.presentation {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("presentation", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| shrike_cbor::cbor_key_cmp(a.0, b.0));
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, shrike_cbor::CborError> {
        let mut decoder = shrike_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(shrike_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut shrike_cbor::Decoder,
    ) -> Result<Self, shrike_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            shrike_cbor::Value::Map(entries) => entries,
            _ => return Err(shrike_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_alt: Option<String> = None;
        let mut field_video: Option<crate::Blob> = None;
        let mut field_captions: Vec<EmbedVideoCaption> = Vec::new();
        let mut field_aspect_ratio: Option<crate::app::bsky::EmbedDefsAspectRatio> = None;
        let mut field_presentation: Option<String> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "alt" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_alt = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "video" => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    let mut dec = shrike_cbor::Decoder::new(&raw);
                    field_video = Some(crate::Blob::decode_cbor(&mut dec)?);
                }
                "captions" => {
                    if let shrike_cbor::Value::Array(items) = value {
                        for item in items {
                            let raw = shrike_cbor::encode_value(&item)?;
                            let mut dec = shrike_cbor::Decoder::new(&raw);
                            field_captions.push(EmbedVideoCaption::decode_cbor(&mut dec)?);
                        }
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected array".into(),
                        ));
                    }
                }
                "aspectRatio" => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    let mut dec = shrike_cbor::Decoder::new(&raw);
                    field_aspect_ratio = Some(crate::app::bsky::EmbedDefsAspectRatio::decode_cbor(
                        &mut dec,
                    )?);
                }
                "presentation" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_presentation = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                _ => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(EmbedVideo {
            alt: field_alt,
            video: field_video.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'video'".into())
            })?,
            captions: field_captions,
            aspect_ratio: field_aspect_ratio,
            presentation: field_presentation,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

/// EmbedVideoView object from app.bsky.embed.video.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EmbedVideoView {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aspect_ratio: Option<crate::app::bsky::EmbedDefsAspectRatio>,
    pub cid: String,
    pub playlist: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub presentation: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<String>,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl EmbedVideoView {
    pub fn to_cbor(&self) -> Result<Vec<u8>, shrike_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), shrike_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 2u64;
            if self.alt.is_some() {
                count += 1;
            }
            if self.thumbnail.is_some() {
                count += 1;
            }
            if self.aspect_ratio.is_some() {
                count += 1;
            }
            if self.presentation.is_some() {
                count += 1;
            }
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            if self.alt.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("alt")?;
                if let Some(ref val) = self.alt {
                    shrike_cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
            shrike_cbor::Encoder::new(&mut *buf).encode_text("cid")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(&self.cid)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("playlist")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(&self.playlist)?;
            if self.thumbnail.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("thumbnail")?;
                if let Some(ref val) = self.thumbnail {
                    shrike_cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
            if self.aspect_ratio.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("aspectRatio")?;
                if let Some(ref val) = self.aspect_ratio {
                    val.encode_cbor(buf)?;
                }
            }
            if self.presentation.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("presentation")?;
                if let Some(ref val) = self.presentation {
                    shrike_cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            if self.alt.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.alt {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("alt", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(&self.cid)?;
                pairs.push(("cid", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(&self.playlist)?;
                pairs.push(("playlist", vbuf));
            }
            if self.thumbnail.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.thumbnail {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("thumbnail", vbuf));
            }
            if self.aspect_ratio.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.aspect_ratio {
                    val.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("aspectRatio", vbuf));
            }
            if self.presentation.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.presentation {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("presentation", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| shrike_cbor::cbor_key_cmp(a.0, b.0));
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, shrike_cbor::CborError> {
        let mut decoder = shrike_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(shrike_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut shrike_cbor::Decoder,
    ) -> Result<Self, shrike_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            shrike_cbor::Value::Map(entries) => entries,
            _ => return Err(shrike_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_alt: Option<String> = None;
        let mut field_cid: Option<String> = None;
        let mut field_playlist: Option<String> = None;
        let mut field_thumbnail: Option<String> = None;
        let mut field_aspect_ratio: Option<crate::app::bsky::EmbedDefsAspectRatio> = None;
        let mut field_presentation: Option<String> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "alt" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_alt = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "cid" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_cid = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "playlist" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_playlist = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "thumbnail" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_thumbnail = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "aspectRatio" => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    let mut dec = shrike_cbor::Decoder::new(&raw);
                    field_aspect_ratio = Some(crate::app::bsky::EmbedDefsAspectRatio::decode_cbor(
                        &mut dec,
                    )?);
                }
                "presentation" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_presentation = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                _ => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(EmbedVideoView {
            alt: field_alt,
            cid: field_cid.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'cid'".into())
            })?,
            playlist: field_playlist.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'playlist'".into())
            })?,
            thumbnail: field_thumbnail,
            aspect_ratio: field_aspect_ratio,
            presentation: field_presentation,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}
