// Code generated by lexgen. DO NOT EDIT.

/// FeedDescribeFeedGeneratorFeed object from app.bsky.feed.describeFeedGenerator.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedDescribeFeedGeneratorFeed {
    pub uri: shrike_syntax::AtUri,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl FeedDescribeFeedGeneratorFeed {
    pub fn to_cbor(&self) -> Result<Vec<u8>, shrike_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), shrike_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let count = 1u64;
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("uri")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(self.uri.as_str())?;
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(self.uri.as_str())?;
                pairs.push(("uri", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| shrike_cbor::cbor_key_cmp(a.0, b.0));
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, shrike_cbor::CborError> {
        let mut decoder = shrike_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(shrike_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut shrike_cbor::Decoder,
    ) -> Result<Self, shrike_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            shrike_cbor::Value::Map(entries) => entries,
            _ => return Err(shrike_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_uri: Option<shrike_syntax::AtUri> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "uri" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_uri =
                            Some(shrike_syntax::AtUri::try_from(s).map_err(|e| {
                                shrike_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                _ => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(FeedDescribeFeedGeneratorFeed {
            uri: field_uri.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'uri'".into())
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

/// FeedDescribeFeedGeneratorLinks object from app.bsky.feed.describeFeedGenerator.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedDescribeFeedGeneratorLinks {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub privacy_policy: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub terms_of_service: Option<String>,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl FeedDescribeFeedGeneratorLinks {
    pub fn to_cbor(&self) -> Result<Vec<u8>, shrike_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), shrike_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 0u64;
            if self.privacy_policy.is_some() {
                count += 1;
            }
            if self.terms_of_service.is_some() {
                count += 1;
            }
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            if self.privacy_policy.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("privacyPolicy")?;
                if let Some(ref val) = self.privacy_policy {
                    shrike_cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
            if self.terms_of_service.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("termsOfService")?;
                if let Some(ref val) = self.terms_of_service {
                    shrike_cbor::Encoder::new(&mut *buf).encode_text(val)?;
                }
            }
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            if self.privacy_policy.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.privacy_policy {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("privacyPolicy", vbuf));
            }
            if self.terms_of_service.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.terms_of_service {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(val)?;
                }
                pairs.push(("termsOfService", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| shrike_cbor::cbor_key_cmp(a.0, b.0));
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, shrike_cbor::CborError> {
        let mut decoder = shrike_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(shrike_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut shrike_cbor::Decoder,
    ) -> Result<Self, shrike_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            shrike_cbor::Value::Map(entries) => entries,
            _ => return Err(shrike_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_privacy_policy: Option<String> = None;
        let mut field_terms_of_service: Option<String> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "privacyPolicy" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_privacy_policy = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "termsOfService" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_terms_of_service = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                _ => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(FeedDescribeFeedGeneratorLinks {
            privacy_policy: field_privacy_policy,
            terms_of_service: field_terms_of_service,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FeedDescribeFeedGeneratorOutput {
    pub did: shrike_syntax::Did,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub feeds: Vec<FeedDescribeFeedGeneratorFeed>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub links: Option<FeedDescribeFeedGeneratorLinks>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// FeedDescribeFeedGenerator — Get information about a feed generator, including policies and offered feed URIs. Does not requir...
pub async fn feed_describe_feed_generator(
    client: &shrike_xrpc::Client,
) -> Result<FeedDescribeFeedGeneratorOutput, shrike_xrpc::Error> {
    client
        .query("app.bsky.feed.describeFeedGenerator", &())
        .await
}
