// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphGetStarterPackParams {
    pub starter_pack: String,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphGetStarterPackOutput {
    pub starter_pack: crate::app::bsky::GraphDefsStarterPackView,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// GraphGetStarterPack — Gets a view of a starter pack.
pub async fn graph_get_starter_pack(
    client: &shrike_xrpc::Client,
    params: &GraphGetStarterPackParams,
) -> Result<GraphGetStarterPackOutput, shrike_xrpc::Error> {
    client.query("app.bsky.graph.getStarterPack", params).await
}
