// Code generated by lexgen. DO NOT EDIT.

/// NSID for the GraphListblock record.
pub const NSID_GRAPH_LISTBLOCK: &str = "app.bsky.graph.listblock";

/// GraphListblock record from app.bsky.graph.listblock.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphListblock {
    pub created_at: shrike_syntax::Datetime,
    pub subject: shrike_syntax::AtUri,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl GraphListblock {
    pub fn to_cbor(&self) -> Result<Vec<u8>, shrike_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), shrike_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let count = 2u64;
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("subject")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(self.subject.as_str())?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("createdAt")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(self.created_at.as_str())?;
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(self.subject.as_str())?;
                pairs.push(("subject", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(self.created_at.as_str())?;
                pairs.push(("createdAt", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| shrike_cbor::cbor_key_cmp(a.0, b.0));
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, shrike_cbor::CborError> {
        let mut decoder = shrike_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(shrike_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut shrike_cbor::Decoder,
    ) -> Result<Self, shrike_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            shrike_cbor::Value::Map(entries) => entries,
            _ => return Err(shrike_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_subject: Option<shrike_syntax::AtUri> = None;
        let mut field_created_at: Option<shrike_syntax::Datetime> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "subject" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_subject =
                            Some(shrike_syntax::AtUri::try_from(s).map_err(|e| {
                                shrike_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "createdAt" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_created_at =
                            Some(shrike_syntax::Datetime::try_from(s).map_err(|e| {
                                shrike_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                _ => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(GraphListblock {
            subject: field_subject.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'subject'".into())
            })?,
            created_at: field_created_at.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'createdAt'".into())
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}
