// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GraphUnmuteActorListInput {
    pub list: shrike_syntax::AtUri,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// GraphUnmuteActorList — Unmutes the specified list of accounts. Requires auth.
pub async fn graph_unmute_actor_list(
    client: &shrike_xrpc::Client,
    input: &GraphUnmuteActorListInput,
) -> Result<(), shrike_xrpc::Error> {
    let _: serde_json::Value = client
        .procedure("app.bsky.graph.unmuteActorList", input)
        .await?;
    Ok(())
}
