// Code generated by lexgen. DO NOT EDIT.

/// LabelerDefsLabelerPolicies object from app.bsky.labeler.defs.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LabelerDefsLabelerPolicies {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub label_value_definitions: Vec<crate::com::atproto::LabelDefsLabelValueDefinition>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub label_values: Vec<crate::com::atproto::LabelDefsLabelValue>,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl LabelerDefsLabelerPolicies {
    pub fn to_cbor(&self) -> Result<Vec<u8>, shrike_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), shrike_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 1u64;
            if !self.label_value_definitions.is_empty() {
                count += 1;
            }
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("labelValues")?;
            shrike_cbor::Encoder::new(&mut *buf)
                .encode_array_header(self.label_values.len() as u64)?;
            for item in &self.label_values {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(item)?;
            }
            if !self.label_value_definitions.is_empty() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("labelValueDefinitions")?;
                shrike_cbor::Encoder::new(&mut *buf)
                    .encode_array_header(self.label_value_definitions.len() as u64)?;
                for item in &self.label_value_definitions {
                    item.encode_cbor(buf)?;
                }
            }
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf)
                    .encode_array_header(self.label_values.len() as u64)?;
                for item in &self.label_values {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(item)?;
                }
                pairs.push(("labelValues", vbuf));
            }
            if !self.label_value_definitions.is_empty() {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf)
                    .encode_array_header(self.label_value_definitions.len() as u64)?;
                for item in &self.label_value_definitions {
                    item.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("labelValueDefinitions", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| shrike_cbor::cbor_key_cmp(a.0, b.0));
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, shrike_cbor::CborError> {
        let mut decoder = shrike_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(shrike_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut shrike_cbor::Decoder,
    ) -> Result<Self, shrike_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            shrike_cbor::Value::Map(entries) => entries,
            _ => return Err(shrike_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_label_values: Vec<crate::com::atproto::LabelDefsLabelValue> = Vec::new();
        let mut field_label_value_definitions: Vec<
            crate::com::atproto::LabelDefsLabelValueDefinition,
        > = Vec::new();
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "labelValues" => {
                    if let shrike_cbor::Value::Array(items) = value {
                        for item in items {
                            if let shrike_cbor::Value::Text(s) = item {
                                field_label_values.push(s.to_string());
                            } else {
                                return Err(shrike_cbor::CborError::InvalidCbor(
                                    "expected text in array".into(),
                                ));
                            }
                        }
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected array".into(),
                        ));
                    }
                }
                "labelValueDefinitions" => {
                    if let shrike_cbor::Value::Array(items) = value {
                        for item in items {
                            let raw = shrike_cbor::encode_value(&item)?;
                            let mut dec = shrike_cbor::Decoder::new(&raw);
                            field_label_value_definitions.push(
                                crate::com::atproto::LabelDefsLabelValueDefinition::decode_cbor(
                                    &mut dec,
                                )?,
                            );
                        }
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected array".into(),
                        ));
                    }
                }
                _ => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(LabelerDefsLabelerPolicies {
            label_values: field_label_values,
            label_value_definitions: field_label_value_definitions,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

/// LabelerDefsLabelerView object from app.bsky.labeler.defs.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LabelerDefsLabelerView {
    pub cid: String,
    pub creator: crate::app::bsky::ActorDefsProfileView,
    pub indexed_at: shrike_syntax::Datetime,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub labels: Vec<crate::com::atproto::LabelDefsLabel>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub like_count: Option<i64>,
    pub uri: shrike_syntax::AtUri,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub viewer: Option<LabelerDefsLabelerViewerState>,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl LabelerDefsLabelerView {
    pub fn to_cbor(&self) -> Result<Vec<u8>, shrike_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), shrike_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 4u64;
            if !self.labels.is_empty() {
                count += 1;
            }
            if self.viewer.is_some() {
                count += 1;
            }
            if self.like_count.is_some() {
                count += 1;
            }
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("cid")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(&self.cid)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("uri")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(self.uri.as_str())?;
            if !self.labels.is_empty() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("labels")?;
                shrike_cbor::Encoder::new(&mut *buf)
                    .encode_array_header(self.labels.len() as u64)?;
                for item in &self.labels {
                    item.encode_cbor(buf)?;
                }
            }
            if self.viewer.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("viewer")?;
                if let Some(ref val) = self.viewer {
                    val.encode_cbor(buf)?;
                }
            }
            shrike_cbor::Encoder::new(&mut *buf).encode_text("creator")?;
            self.creator.encode_cbor(buf)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("indexedAt")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(self.indexed_at.as_str())?;
            if self.like_count.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("likeCount")?;
                if let Some(ref val) = self.like_count {
                    shrike_cbor::Encoder::new(&mut *buf).encode_i64(*val)?;
                }
            }
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(&self.cid)?;
                pairs.push(("cid", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(self.uri.as_str())?;
                pairs.push(("uri", vbuf));
            }
            if !self.labels.is_empty() {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf)
                    .encode_array_header(self.labels.len() as u64)?;
                for item in &self.labels {
                    item.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("labels", vbuf));
            }
            if self.viewer.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.viewer {
                    val.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("viewer", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                self.creator.encode_cbor(&mut vbuf)?;
                pairs.push(("creator", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(self.indexed_at.as_str())?;
                pairs.push(("indexedAt", vbuf));
            }
            if self.like_count.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.like_count {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_i64(*val)?;
                }
                pairs.push(("likeCount", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| shrike_cbor::cbor_key_cmp(a.0, b.0));
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, shrike_cbor::CborError> {
        let mut decoder = shrike_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(shrike_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut shrike_cbor::Decoder,
    ) -> Result<Self, shrike_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            shrike_cbor::Value::Map(entries) => entries,
            _ => return Err(shrike_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_cid: Option<String> = None;
        let mut field_uri: Option<shrike_syntax::AtUri> = None;
        let mut field_labels: Vec<crate::com::atproto::LabelDefsLabel> = Vec::new();
        let mut field_viewer: Option<LabelerDefsLabelerViewerState> = None;
        let mut field_creator: Option<crate::app::bsky::ActorDefsProfileView> = None;
        let mut field_indexed_at: Option<shrike_syntax::Datetime> = None;
        let mut field_like_count: Option<i64> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "cid" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_cid = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "uri" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_uri =
                            Some(shrike_syntax::AtUri::try_from(s).map_err(|e| {
                                shrike_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "labels" => {
                    if let shrike_cbor::Value::Array(items) = value {
                        for item in items {
                            let raw = shrike_cbor::encode_value(&item)?;
                            let mut dec = shrike_cbor::Decoder::new(&raw);
                            field_labels
                                .push(crate::com::atproto::LabelDefsLabel::decode_cbor(&mut dec)?);
                        }
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected array".into(),
                        ));
                    }
                }
                "viewer" => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    let mut dec = shrike_cbor::Decoder::new(&raw);
                    field_viewer = Some(LabelerDefsLabelerViewerState::decode_cbor(&mut dec)?);
                }
                "creator" => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    let mut dec = shrike_cbor::Decoder::new(&raw);
                    field_creator = Some(crate::app::bsky::ActorDefsProfileView::decode_cbor(
                        &mut dec,
                    )?);
                }
                "indexedAt" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_indexed_at =
                            Some(shrike_syntax::Datetime::try_from(s).map_err(|e| {
                                shrike_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "likeCount" => match value {
                    shrike_cbor::Value::Unsigned(n) => {
                        field_like_count = Some(n as i64);
                    }
                    shrike_cbor::Value::Signed(n) => {
                        field_like_count = Some(n);
                    }
                    _ => {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected integer".into(),
                        ));
                    }
                },
                _ => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(LabelerDefsLabelerView {
            cid: field_cid.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'cid'".into())
            })?,
            uri: field_uri.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'uri'".into())
            })?,
            labels: field_labels,
            viewer: field_viewer,
            creator: field_creator.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'creator'".into())
            })?,
            indexed_at: field_indexed_at.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'indexedAt'".into())
            })?,
            like_count: field_like_count,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

/// LabelerDefsLabelerViewDetailed object from app.bsky.labeler.defs.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LabelerDefsLabelerViewDetailed {
    pub cid: String,
    pub creator: crate::app::bsky::ActorDefsProfileView,
    pub indexed_at: shrike_syntax::Datetime,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub labels: Vec<crate::com::atproto::LabelDefsLabel>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub like_count: Option<i64>,
    pub policies: LabelerDefsLabelerPolicies,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub reason_types: Vec<crate::com::atproto::ModerationDefsReasonType>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub subject_collections: Vec<shrike_syntax::Nsid>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub subject_types: Vec<crate::com::atproto::ModerationDefsSubjectType>,
    pub uri: shrike_syntax::AtUri,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub viewer: Option<LabelerDefsLabelerViewerState>,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl LabelerDefsLabelerViewDetailed {
    pub fn to_cbor(&self) -> Result<Vec<u8>, shrike_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), shrike_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 5u64;
            if !self.labels.is_empty() {
                count += 1;
            }
            if self.viewer.is_some() {
                count += 1;
            }
            if self.like_count.is_some() {
                count += 1;
            }
            if !self.reason_types.is_empty() {
                count += 1;
            }
            if !self.subject_types.is_empty() {
                count += 1;
            }
            if !self.subject_collections.is_empty() {
                count += 1;
            }
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("cid")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(&self.cid)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("uri")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(self.uri.as_str())?;
            if !self.labels.is_empty() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("labels")?;
                shrike_cbor::Encoder::new(&mut *buf)
                    .encode_array_header(self.labels.len() as u64)?;
                for item in &self.labels {
                    item.encode_cbor(buf)?;
                }
            }
            if self.viewer.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("viewer")?;
                if let Some(ref val) = self.viewer {
                    val.encode_cbor(buf)?;
                }
            }
            shrike_cbor::Encoder::new(&mut *buf).encode_text("creator")?;
            self.creator.encode_cbor(buf)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("policies")?;
            self.policies.encode_cbor(buf)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("indexedAt")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(self.indexed_at.as_str())?;
            if self.like_count.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("likeCount")?;
                if let Some(ref val) = self.like_count {
                    shrike_cbor::Encoder::new(&mut *buf).encode_i64(*val)?;
                }
            }
            if !self.reason_types.is_empty() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("reasonTypes")?;
                shrike_cbor::Encoder::new(&mut *buf)
                    .encode_array_header(self.reason_types.len() as u64)?;
                for item in &self.reason_types {
                    shrike_cbor::Encoder::new(&mut *buf).encode_text(item)?;
                }
            }
            if !self.subject_types.is_empty() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("subjectTypes")?;
                shrike_cbor::Encoder::new(&mut *buf)
                    .encode_array_header(self.subject_types.len() as u64)?;
                for item in &self.subject_types {
                    shrike_cbor::Encoder::new(&mut *buf).encode_text(item)?;
                }
            }
            if !self.subject_collections.is_empty() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("subjectCollections")?;
                shrike_cbor::Encoder::new(&mut *buf)
                    .encode_array_header(self.subject_collections.len() as u64)?;
                for item in &self.subject_collections {
                    shrike_cbor::Encoder::new(&mut *buf).encode_text(item.as_str())?;
                }
            }
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(&self.cid)?;
                pairs.push(("cid", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(self.uri.as_str())?;
                pairs.push(("uri", vbuf));
            }
            if !self.labels.is_empty() {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf)
                    .encode_array_header(self.labels.len() as u64)?;
                for item in &self.labels {
                    item.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("labels", vbuf));
            }
            if self.viewer.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.viewer {
                    val.encode_cbor(&mut vbuf)?;
                }
                pairs.push(("viewer", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                self.creator.encode_cbor(&mut vbuf)?;
                pairs.push(("creator", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                self.policies.encode_cbor(&mut vbuf)?;
                pairs.push(("policies", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(self.indexed_at.as_str())?;
                pairs.push(("indexedAt", vbuf));
            }
            if self.like_count.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.like_count {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_i64(*val)?;
                }
                pairs.push(("likeCount", vbuf));
            }
            if !self.reason_types.is_empty() {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf)
                    .encode_array_header(self.reason_types.len() as u64)?;
                for item in &self.reason_types {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(item)?;
                }
                pairs.push(("reasonTypes", vbuf));
            }
            if !self.subject_types.is_empty() {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf)
                    .encode_array_header(self.subject_types.len() as u64)?;
                for item in &self.subject_types {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(item)?;
                }
                pairs.push(("subjectTypes", vbuf));
            }
            if !self.subject_collections.is_empty() {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf)
                    .encode_array_header(self.subject_collections.len() as u64)?;
                for item in &self.subject_collections {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(item.as_str())?;
                }
                pairs.push(("subjectCollections", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| shrike_cbor::cbor_key_cmp(a.0, b.0));
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, shrike_cbor::CborError> {
        let mut decoder = shrike_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(shrike_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut shrike_cbor::Decoder,
    ) -> Result<Self, shrike_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            shrike_cbor::Value::Map(entries) => entries,
            _ => return Err(shrike_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_cid: Option<String> = None;
        let mut field_uri: Option<shrike_syntax::AtUri> = None;
        let mut field_labels: Vec<crate::com::atproto::LabelDefsLabel> = Vec::new();
        let mut field_viewer: Option<LabelerDefsLabelerViewerState> = None;
        let mut field_creator: Option<crate::app::bsky::ActorDefsProfileView> = None;
        let mut field_policies: Option<LabelerDefsLabelerPolicies> = None;
        let mut field_indexed_at: Option<shrike_syntax::Datetime> = None;
        let mut field_like_count: Option<i64> = None;
        let mut field_reason_types: Vec<crate::com::atproto::ModerationDefsReasonType> = Vec::new();
        let mut field_subject_types: Vec<crate::com::atproto::ModerationDefsSubjectType> =
            Vec::new();
        let mut field_subject_collections: Vec<shrike_syntax::Nsid> = Vec::new();
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "cid" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_cid = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "uri" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_uri =
                            Some(shrike_syntax::AtUri::try_from(s).map_err(|e| {
                                shrike_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "labels" => {
                    if let shrike_cbor::Value::Array(items) = value {
                        for item in items {
                            let raw = shrike_cbor::encode_value(&item)?;
                            let mut dec = shrike_cbor::Decoder::new(&raw);
                            field_labels
                                .push(crate::com::atproto::LabelDefsLabel::decode_cbor(&mut dec)?);
                        }
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected array".into(),
                        ));
                    }
                }
                "viewer" => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    let mut dec = shrike_cbor::Decoder::new(&raw);
                    field_viewer = Some(LabelerDefsLabelerViewerState::decode_cbor(&mut dec)?);
                }
                "creator" => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    let mut dec = shrike_cbor::Decoder::new(&raw);
                    field_creator = Some(crate::app::bsky::ActorDefsProfileView::decode_cbor(
                        &mut dec,
                    )?);
                }
                "policies" => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    let mut dec = shrike_cbor::Decoder::new(&raw);
                    field_policies = Some(LabelerDefsLabelerPolicies::decode_cbor(&mut dec)?);
                }
                "indexedAt" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_indexed_at =
                            Some(shrike_syntax::Datetime::try_from(s).map_err(|e| {
                                shrike_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                "likeCount" => match value {
                    shrike_cbor::Value::Unsigned(n) => {
                        field_like_count = Some(n as i64);
                    }
                    shrike_cbor::Value::Signed(n) => {
                        field_like_count = Some(n);
                    }
                    _ => {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected integer".into(),
                        ));
                    }
                },
                "reasonTypes" => {
                    if let shrike_cbor::Value::Array(items) = value {
                        for item in items {
                            if let shrike_cbor::Value::Text(s) = item {
                                field_reason_types.push(s.to_string());
                            } else {
                                return Err(shrike_cbor::CborError::InvalidCbor(
                                    "expected text in array".into(),
                                ));
                            }
                        }
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected array".into(),
                        ));
                    }
                }
                "subjectTypes" => {
                    if let shrike_cbor::Value::Array(items) = value {
                        for item in items {
                            if let shrike_cbor::Value::Text(s) = item {
                                field_subject_types.push(s.to_string());
                            } else {
                                return Err(shrike_cbor::CborError::InvalidCbor(
                                    "expected text in array".into(),
                                ));
                            }
                        }
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected array".into(),
                        ));
                    }
                }
                "subjectCollections" => {
                    if let shrike_cbor::Value::Array(items) = value {
                        for item in items {
                            if let shrike_cbor::Value::Text(s) = item {
                                field_subject_collections.push(
                                    shrike_syntax::Nsid::try_from(s).map_err(|e| {
                                        shrike_cbor::CborError::InvalidCbor(e.to_string())
                                    })?,
                                );
                            } else {
                                return Err(shrike_cbor::CborError::InvalidCbor(
                                    "expected text in array".into(),
                                ));
                            }
                        }
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected array".into(),
                        ));
                    }
                }
                _ => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(LabelerDefsLabelerViewDetailed {
            cid: field_cid.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'cid'".into())
            })?,
            uri: field_uri.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'uri'".into())
            })?,
            labels: field_labels,
            viewer: field_viewer,
            creator: field_creator.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'creator'".into())
            })?,
            policies: field_policies.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'policies'".into())
            })?,
            indexed_at: field_indexed_at.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'indexedAt'".into())
            })?,
            like_count: field_like_count,
            reason_types: field_reason_types,
            subject_types: field_subject_types,
            subject_collections: field_subject_collections,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}

/// LabelerDefsLabelerViewerState object from app.bsky.labeler.defs.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LabelerDefsLabelerViewerState {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub like: Option<shrike_syntax::AtUri>,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl LabelerDefsLabelerViewerState {
    pub fn to_cbor(&self) -> Result<Vec<u8>, shrike_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), shrike_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let mut count = 0u64;
            if self.like.is_some() {
                count += 1;
            }
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            if self.like.is_some() {
                shrike_cbor::Encoder::new(&mut *buf).encode_text("like")?;
                if let Some(ref val) = self.like {
                    shrike_cbor::Encoder::new(&mut *buf).encode_text(val.as_str())?;
                }
            }
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            if self.like.is_some() {
                let mut vbuf = Vec::new();
                if let Some(ref val) = self.like {
                    shrike_cbor::Encoder::new(&mut vbuf).encode_text(val.as_str())?;
                }
                pairs.push(("like", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| shrike_cbor::cbor_key_cmp(a.0, b.0));
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, shrike_cbor::CborError> {
        let mut decoder = shrike_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(shrike_cbor::CborError::InvalidCbor(
                "trailing data".into(),
            ));
        }
        Ok(result)
    }

    pub fn decode_cbor(
        decoder: &mut shrike_cbor::Decoder,
    ) -> Result<Self, shrike_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            shrike_cbor::Value::Map(entries) => entries,
            _ => return Err(shrike_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_like: Option<shrike_syntax::AtUri> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "like" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_like =
                            Some(shrike_syntax::AtUri::try_from(s).map_err(|e| {
                                shrike_cbor::CborError::InvalidCbor(e.to_string())
                            })?);
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor(
                            "expected text".into(),
                        ));
                    }
                }
                _ => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(LabelerDefsLabelerViewerState {
            like: field_like,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}
