// Code generated by lexgen. DO NOT EDIT.

#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnspeccedGetTaggedSuggestionsParams {}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnspeccedGetTaggedSuggestionsOutput {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub suggestions: Vec<UnspeccedGetTaggedSuggestionsSuggestion>,
    /// Extra fields not defined in the schema.
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
}

/// UnspeccedGetTaggedSuggestions — Get a list of suggestions (feeds and users) tagged with categories
pub async fn unspecced_get_tagged_suggestions(
    client: &shrike_xrpc::Client,
    params: &UnspeccedGetTaggedSuggestionsParams,
) -> Result<UnspeccedGetTaggedSuggestionsOutput, shrike_xrpc::Error> {
    client
        .query("app.bsky.unspecced.getTaggedSuggestions", params)
        .await
}

/// UnspeccedGetTaggedSuggestionsSuggestion object from app.bsky.unspecced.getTaggedSuggestions.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnspeccedGetTaggedSuggestionsSuggestion {
    pub subject: String,
    pub subject_type: String,
    pub tag: String,
    /// Extra fields not defined in the schema (JSON).
    #[serde(flatten)]
    pub extra: std::collections::HashMap<String, serde_json::Value>,
    /// Extra fields not defined in the schema (CBOR).
    #[serde(skip)]
    pub extra_cbor: Vec<(String, Vec<u8>)>,
}

impl UnspeccedGetTaggedSuggestionsSuggestion {
    pub fn to_cbor(&self) -> Result<Vec<u8>, shrike_cbor::CborError> {
        let mut buf = Vec::new();
        self.encode_cbor(&mut buf)?;
        Ok(buf)
    }

    pub fn encode_cbor(&self, buf: &mut Vec<u8>) -> Result<(), shrike_cbor::CborError> {
        if self.extra_cbor.is_empty() {
            // Fast path: no extra fields to merge.
            let count = 3u64;
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(count)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("tag")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(&self.tag)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("subject")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(&self.subject)?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text("subjectType")?;
            shrike_cbor::Encoder::new(&mut *buf).encode_text(&self.subject_type)?;
        } else {
            // Slow path: merge known fields with extra_cbor, sort, encode.
            let mut pairs: Vec<(&str, Vec<u8>)> = Vec::new();
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(&self.tag)?;
                pairs.push(("tag", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(&self.subject)?;
                pairs.push(("subject", vbuf));
            }
            {
                let mut vbuf = Vec::new();
                shrike_cbor::Encoder::new(&mut vbuf).encode_text(&self.subject_type)?;
                pairs.push(("subjectType", vbuf));
            }
            for (k, v) in &self.extra_cbor {
                pairs.push((k.as_str(), v.clone()));
            }
            pairs.sort_by(|a, b| shrike_cbor::cbor_key_cmp(a.0, b.0));
            shrike_cbor::Encoder::new(&mut *buf).encode_map_header(pairs.len() as u64)?;
            for (k, v) in &pairs {
                shrike_cbor::Encoder::new(&mut *buf).encode_text(k)?;
                buf.extend_from_slice(v);
            }
        }
        Ok(())
    }

    pub fn from_cbor(data: &[u8]) -> Result<Self, shrike_cbor::CborError> {
        let mut decoder = shrike_cbor::Decoder::new(data);
        let result = Self::decode_cbor(&mut decoder)?;
        if !decoder.is_empty() {
            return Err(shrike_cbor::CborError::InvalidCbor("trailing data".into()));
        }
        Ok(result)
    }

    pub fn decode_cbor(decoder: &mut shrike_cbor::Decoder) -> Result<Self, shrike_cbor::CborError> {
        let val = decoder.decode()?;
        let entries = match val {
            shrike_cbor::Value::Map(entries) => entries,
            _ => return Err(shrike_cbor::CborError::InvalidCbor("expected map".into())),
        };

        let mut field_tag: Option<String> = None;
        let mut field_subject: Option<String> = None;
        let mut field_subject_type: Option<String> = None;
        let mut extra_cbor: Vec<(String, Vec<u8>)> = Vec::new();

        for (key, value) in entries {
            match key {
                "tag" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_tag = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "subject" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_subject = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                "subjectType" => {
                    if let shrike_cbor::Value::Text(s) = value {
                        field_subject_type = Some(s.to_string());
                    } else {
                        return Err(shrike_cbor::CborError::InvalidCbor("expected text".into()));
                    }
                }
                _ => {
                    let raw = shrike_cbor::encode_value(&value)?;
                    extra_cbor.push((key.to_string(), raw));
                }
            }
        }

        Ok(UnspeccedGetTaggedSuggestionsSuggestion {
            tag: field_tag.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'tag'".into())
            })?,
            subject: field_subject.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'subject'".into())
            })?,
            subject_type: field_subject_type.ok_or_else(|| {
                shrike_cbor::CborError::InvalidCbor("missing required field 'subjectType'".into())
            })?,
            extra: std::collections::HashMap::new(),
            extra_cbor,
        })
    }
}
