name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: Check formatting
        run: nix develop --command just fmt

      - name: Clippy
        run: nix develop --command cargo clippy --workspace --features full --tests -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: Build
        run: nix develop --command just build

      - name: Test
        run: nix develop --command just test

      - name: Test docs
        run: nix develop --command just test-docs
